import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import test from 'node:test';

import {findMarkdownHeadings, parseFrontMatter, readContentDocuments} from '../scripts/content-metadata.mjs';
import {extractInternalLinks} from '../scripts/content-relations.mjs';
import {architectureCaseTopicIds, knowledgeHeadingContract} from '../scripts/content-schema.mjs';

export const ARTICLE = 'content/styles/sty-11-serverless-architecture.mdx';
export const DRAWIO = 'diagrams/sty-11-serverless-order-fulfillment.drawio';
export const SVG = 'static/img/diagrams/sty-11-serverless-order-fulfillment.svg';
export const ROUTE = '/styles/sty-11'; export const TOPIC_ID = 'STY-11'; export const NEXT_TOPIC = 'STY-12'; export const RELATED_CASE = '/cases/cloudflare-durable-objects-workerd';
export const EXPECTED_STAGE_A = Object.freeze({completed: 63, documents: 107, sources: 560});
export const SOURCE_IDS = Object.freeze(['src-cncf-serverless-whitepaper-v1','src-cncf-serverless-glossary','src-aws-lambda-runtime-lifecycle','src-aws-lambda-invocation-retries','src-aws-lambda-concurrency','src-aws-lambda-pricing','src-azure-functions-scale-hosting','src-google-cloud-run-concurrency','src-cncf-cloudevents-102-spec','src-open-workflow-specification-103','src-atlas-sty11-serverless-order-fulfillment']);
export const EXACT_METADATA = Object.freeze({title: 'Serverless Architecture：把运行责任交给平台，不把业务边界一并交出去', slug: '/styles/sty-11', content_type: 'style', status: 'reviewed', difficulty: 'advanced', analyzed_at: '2026-08-25', source_cutoff: '2026-08-25', confidence: 'high', domains: ['software-architecture', 'distributed-systems', 'platform-engineering'], agent_patterns: [], protocols: [], quality_attributes: ['scalability', 'performance', 'reliability', 'recoverability', 'operability', 'cost-efficiency'], tags: ['架构风格', 'Serverless', 'FaaS', '事件驱动', '幂等', '冷启动', '成本治理'], summary: '以订单结算与异步履约说明 Serverless：同步入口只受理，持久工作流保存进度，队列和三层并发预算保护下游，有界函数执行单步任务，并把冷启动、成本与供应商退出放进同一决策。', topic_id: 'STY-11', priority: 'P1', depends_on: ['STY-00', 'STY-06'], adjacent_topics: ['STY-06', 'STY-09'], related_cases: [RELATED_CASE], related_questions: []});
export const EXPECTED_HEADINGS = Object.freeze(['学习问题','一页摘要','事实边界','架构图','控制权与任务流','关键源码导读','架构决策与权衡','生产化分析','可迁移经验','来源']);
export const MIGRATION_HEADINGS = Object.freeze(['可直接复用的机制','只能有限类比的部分','不应照搬的部分']);
export const WRAPPERS = Object.freeze(['订单结算与异步履约 Serverless 边界图，可横向滚动','Serverless 执行与状态责任矩阵，可横向滚动','Serverless 七类故障、响应、停止条件与责任表，可横向滚动','冷启动与成本决策表，可横向滚动']);
export const OWNERSHIP_ROWS = Object.freeze([['同步入口函数','认证、校验、幂等受理','受理记录与操作标识','整条履约进度'],['持久工作流','步骤、期限、重试、补偿、终态','状态版本与步骤回执','支付或库存账本'],['队列与任务分发','缓冲、重投递、消费限速','消息与投递状态','业务成功结论'],['步骤函数','执行一个支付、库存或通知任务','只写回标准结果或回执','长流程状态与无限重试'],['订单状态记录','保存订单权威进度','订单版本、阶段与关联回执','下游业务事实'],['权威下游系统','原子判定支付、库存或投递结果','各自账本与结果查询','订单流程编排'],['容量与成本观测','关联延迟、并发、节流与费用','可审计的观测与归因记录','自动改变业务终态']]);
export const ORDER_FLOW = Object.freeze(['认证与幂等受理','返回订单操作标识','生成支付任务','受控交付支付任务','记录支付回执或查询结果','条件状态转移','库存权威原子判定','订单提交后异步通知','记录端到端容量账本']);
export const CONCURRENCY_LAYERS = Object.freeze(['入口层','执行层','下游层']);
export const FAILURE_ROWS = Object.freeze([['重复或乱序交付','相同幂等键、陈旧状态版本或乱序步骤','幂等查重、条件状态转移、丢弃陈旧版本','事件无法关联订单或状态版本','订单域负责人'],['队列积压与函数节流','队列深度、最老任务年龄、节流和业务期限','降低入口、限制消费、保护下游并告警','业务期限已无法满足','平台运行负责人'],['冷启动导致同步超时','初始化时长、尾延迟、客户端断开','预算内重试或使用预置容量；异步步骤继续查状态','客户端期限耗尽或结果未知','接口与容量负责人'],['支付或库存结果未知','调用超时、连接中断、缺少确定回执','用业务操作标识查询权威系统并对账','无法证明是否已产生外部效果','支付或库存域负责人'],['毒任务或确定性业务错误','同一输入与版本重复确定失败','隔离任务并保留输入、版本和尝试证据','重试不会改变结果','对应业务能力负责人'],['重试风暴或成本异常','调用放大、并发、错误率和费用预算','熔断、降低并发、暂停非关键步骤和新流量','单订单或时间窗预算耗尽','FinOps 与平台负责人'],['托管工作流或区域故障','工作流不可用、检查点中断或区域信号','停止新推进，依据持久检查点恢复或切换','状态副本、事件顺序或外部回执不可信','业务连续性负责人']]);
export const COLD_COST_ROWS = Object.freeze([['少量同步请求尾延迟升高','初始化与下游等待各占多少','缩小依赖、延迟非必要初始化','初始化持续击穿业务期限'],['突发流量产生冷启动','入口速率、并发和下游预算','缓冲、限流、调整并发','同步请求不可缓冲且期限严格'],['预置容量利用率低','时段分布和空闲费用','调低或按时段调度','业务要求全时段稳定低延迟'],['异步任务处理变慢','队列年龄、消费速率和业务期限','调整消费与批量，保护下游','最老任务接近不可逆期限'],['持续高负载且波动小','单位成本、利用率和运维成本','比较按量函数与常驻服务','常驻服务在约束内更可预测']]);
export const IDENTITY_SEMANTICS = Object.freeze([
  ['入口幂等键', '收敛重复受理'], ['订单操作标识', '返回同一受理结果'], ['步骤操作标识', '查询真实结果'], ['事件标识', '只标识一次投递'],
]);
export const APPLICABILITY_SIGNALS = Object.freeze(['事件驱动负载', '明显峰谷', '有界任务', '可拆分状态', '能够接受托管服务约束']);
export const STOP_ADOPTION_CONDITIONS = Object.freeze(['持续稳定高负载', '极严格且无法吸收的尾延迟', '长时间计算', '需要本地专用资源', '跨步骤共享内存或事务', '执行模型与运行时限制不兼容', '团队无法运营队列、幂等、成本和人工恢复', '迁移所需状态和外部回执不能导出', '供应商专有语义已经无法被业务合同解释或验证']);
export const REGION_IDS = Object.freeze(['request-boundary','durable-control','function-execution','authority-boundary']);
export const NODE_IDS = Object.freeze(['client','sync-ingress','admission-store','durable-workflow','order-state','task-queue','payment-function','inventory-function','notification-function','payment-authority','inventory-authority','notification-provider','capacity-cost-observability','reconciliation','manual-terminal']);
export const EDGE_IDS = Object.freeze(['submit-order','idempotent-accept','start-workflow','read-order-state','enqueue-payment','deliver-payment','invoke-payment','payment-receipt','enqueue-inventory','deliver-inventory','reserve-inventory','inventory-receipt','enqueue-notification','deliver-notification','send-notification','query-unknown-result','reconcile-manually','close-manual-terminal','limit-ingress','limit-execution','limit-downstream']);
export const LEGEND_ROLES = Object.freeze(['request','work','receipt','recovery','budget']);
export const EDGE_CONTRACTS = Object.freeze({
  'submit-order': ['client','sync-ingress','request'], 'idempotent-accept': ['sync-ingress','admission-store','request'], 'start-workflow': ['sync-ingress','durable-workflow','request'], 'read-order-state': ['durable-workflow','order-state','receipt'],
  'enqueue-payment': ['durable-workflow','task-queue','work'], 'deliver-payment': ['task-queue','payment-function','work'], 'invoke-payment': ['payment-function','payment-authority','work'], 'payment-receipt': ['payment-authority','durable-workflow','receipt'],
  'enqueue-inventory': ['durable-workflow','task-queue','work'], 'deliver-inventory': ['task-queue','inventory-function','work'], 'reserve-inventory': ['inventory-function','inventory-authority','work'], 'inventory-receipt': ['inventory-authority','durable-workflow','receipt'],
  'enqueue-notification': ['durable-workflow','task-queue','work'], 'deliver-notification': ['task-queue','notification-function','work'], 'send-notification': ['notification-function','notification-provider','work'],
  'query-unknown-result': ['durable-workflow','reconciliation','recovery'], 'reconcile-manually': ['reconciliation','manual-terminal','recovery'], 'close-manual-terminal': ['manual-terminal','order-state','recovery'],
  'limit-ingress': ['capacity-cost-observability','sync-ingress','budget'], 'limit-execution': ['capacity-cost-observability','task-queue','budget'], 'limit-downstream': ['capacity-cost-observability','payment-authority','budget'],
});
export const REMOTE_SOURCES = Object.freeze({
  'src-cncf-serverless-whitepaper-v1': {canonical_locator: 'https://github.com/cncf/wg-serverless/blob/79c8a13c26be9066a8723c5896d8aaa0e2ab9e08/whitepapers/serverless-overview/cncf_serverless_whitepaper_v1.0.pdf', transport_locator: 'https://raw.githubusercontent.com/cncf/wg-serverless/79c8a13c26be9066a8723c5896d8aaa0e2ab9e08/whitepapers/serverless-overview/cncf_serverless_whitepaper_v1.0.pdf', version: 'cncf/wg-serverless@79c8a13c26be9066a8723c5896d8aaa0e2ab9e08; checked 2026-08-25', license: 'Apache-2.0', copyright_policy: 'facts-and-short-quotation', roles: ['definition'], usage_boundary: 'Supports the Serverless scope, platform execution, scaling and billing definition only; it does not prove any provider behavior, order outcome, portability, or production guarantee.'},
  'src-cncf-serverless-glossary': {canonical_locator: 'https://glossary.cncf.io/serverless/', transport_locator: 'https://glossary.cncf.io/serverless/', version: 'cncf/glossary@334ce7e82d20cd8cdcd12bc828d12cc518be0f19; checked 2026-08-25', license: 'CC-BY-4.0', copyright_policy: 'facts-and-short-quotation', roles: ['definition'], usage_boundary: 'Supports Serverless terminology and scope only; it does not prove provider runtime behavior, business guarantees, or the original order scenario.'},
  'src-aws-lambda-runtime-lifecycle': {canonical_locator: 'https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtime-environment.html', transport_locator: 'https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtime-environment.html', version: 'checked 2026-08-25', license: 'LicenseRef-All-Rights-Reserved', copyright_policy: 'facts-summary', roles: ['runtime-fact'], usage_boundary: 'Supports Lambda execution-environment initialization, invocation, reuse and reset mechanisms only; it does not generalize to all Serverless runtimes.'},
  'src-aws-lambda-invocation-retries': {canonical_locator: 'https://docs.aws.amazon.com/lambda/latest/dg/invocation-retries.html', transport_locator: 'https://docs.aws.amazon.com/lambda/latest/dg/invocation-retries.html', version: 'checked 2026-08-25', license: 'LicenseRef-All-Rights-Reserved', copyright_policy: 'facts-summary', roles: ['mechanism'], usage_boundary: 'Supports invocation-mode retry, duplicate-delivery and backlog mechanisms only; it does not establish exactly-once or universal retry parameters.'},
  'src-aws-lambda-concurrency': {canonical_locator: 'https://docs.aws.amazon.com/lambda/latest/dg/lambda-concurrency.html', transport_locator: 'https://docs.aws.amazon.com/lambda/latest/dg/lambda-concurrency.html', version: 'checked 2026-08-25', license: 'LicenseRef-All-Rights-Reserved', copyright_policy: 'facts-summary', roles: ['mechanism'], usage_boundary: 'Supports Lambda concurrency and provisioned-concurrency mechanisms only; it does not prove infinite application capacity or a downstream budget.'},
  'src-aws-lambda-pricing': {canonical_locator: 'https://aws.amazon.com/lambda/pricing/', transport_locator: 'https://aws.amazon.com/lambda/pricing/', version: 'checked 2026-08-25', license: 'LicenseRef-All-Rights-Reserved', copyright_policy: 'facts-summary', roles: ['cost-boundary'], usage_boundary: 'Supports Lambda billing dimensions only; it does not support durable price comparisons, regional cost conclusions, or the article cost model.'},
  'src-azure-functions-scale-hosting': {canonical_locator: 'https://learn.microsoft.com/en-us/azure/azure-functions/functions-scale', transport_locator: 'https://learn.microsoft.com/en-us/azure/azure-functions/functions-scale', version: 'checked 2026-08-25', license: 'LicenseRef-All-Rights-Reserved', copyright_policy: 'facts-summary', roles: ['comparison'], usage_boundary: 'Supports Azure Functions scale and hosting-plan mechanisms only; it does not generalize plan names or limits to other providers.'},
  'src-google-cloud-run-concurrency': {canonical_locator: 'https://cloud.google.com/run/docs/about-concurrency', transport_locator: 'https://docs.cloud.google.com/run/docs/about-concurrency', version: 'checked 2026-08-25', license: 'CC-BY-4.0', copyright_policy: 'facts-summary', roles: ['comparison'], usage_boundary: 'Supports Cloud Run per-instance concurrency and concurrency-safe code requirements only; it does not equate Cloud Run with all FaaS runtimes.'},
  'src-cncf-cloudevents-102-spec': {canonical_locator: 'https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md', transport_locator: 'https://raw.githubusercontent.com/cloudevents/spec/v1.0.2/cloudevents/spec.md', version: 'v1.0.2', license: 'Apache-2.0', copyright_policy: 'facts-and-short-quotation', roles: ['definition', 'implementation', 'method'], usage_boundary: 'Supports protocol-independent CloudEvents context attributes and envelope semantics only; it does not establish the article\'s four-mode business taxonomy, state ownership, or production guarantees.'},
  'src-open-workflow-specification-103': {canonical_locator: 'https://github.com/open-workflow-specification/specification/blob/2dd2c84170d5f3e05d58e913e9ca298dcf8d543a/schema/workflow.yaml', transport_locator: 'https://raw.githubusercontent.com/open-workflow-specification/specification/2dd2c84170d5f3e05d58e913e9ca298dcf8d543a/schema/workflow.yaml', version: 'Open Workflow Specification 1.0.3; commit 2dd2c84170d5f3e05d58e913e9ca298dcf8d543a; checked 2026-08-25', license: 'Apache-2.0', copyright_policy: 'facts-and-short-quotation', roles: ['portability-boundary'], usage_boundary: 'Supports vendor-neutral workflow description for events, tasks, timeouts, errors and retries only; it does not establish equivalent runtime durability, recovery, or migration semantics.'},
});
export const ORIGINAL_SOURCE = Object.freeze({canonical_locator: '/img/diagrams/sty-11-serverless-order-fulfillment.svg', transport_locator: '/img/diagrams/sty-11-serverless-order-fulfillment.svg', version: 'original-atlas; created 2026-08-25', license: 'LicenseRef-Atlas-Original', copyright_policy: 'original-atlas', roles: ['illustration'], usage_boundary: 'Original teaching topology for Serverless order acceptance, durable control, bounded functions, authority boundaries, recovery, and capacity budgets; illustration-only and not evidence of production outcomes.'});
const CONTENT_ROOT = fileURLToPath(new URL('../content/', import.meta.url));
function file(path) { try { return readFileSync(path, 'utf8'); } catch (error) { if (error?.code === 'ENOENT') return undefined; throw error; } }
function escapeRegExp(value) { return value.replace(/[.*+?^${}()|[\]\\]/gu, '\\$&'); }
function articleParts(source) { assert.ok(source, `${ARTICLE} must exist after implementation`); const close = source.indexOf('\n---', 3); assert.ok(close >= 0, 'front matter closes'); return {source, body: source.slice(close + 4)}; }
function exactWrapper(label) { return `<div role="region" aria-label="${label}" tabIndex={0} onKeyDown={handleHorizontalArrowKey}>`; }
function replaceOnce(source, oldValue, newValue, label) { const changed = source.replace(oldValue, newValue); assert.notEqual(changed, source, `${label} mutation applies`); return changed; }
function mutateDrawioCell(source, id, mutate, label) { const cell = parseDrawio(source).cells.find(({attributes: item}) => item.get('id') === id); assert.ok(cell, `${label} fixture cell`); const changed = mutate(cell.raw); assert.notEqual(changed, cell.raw, `${label} mutation applies`); return replaceOnce(source, cell.raw, changed, label); }
function mutateSvgElement(source, predicate, mutate, label) { const element = parseSvg(source).elements.find(predicate); assert.ok(element, `${label} fixture element`); const open = source.slice(element.sourceIndex, element.openEnd); const changed = mutate(open); assert.notEqual(changed, open, `${label} mutation applies`); return `${source.slice(0, element.sourceIndex)}${changed}${source.slice(element.openEnd)}`; }
function mutateSvgText(source, predicate, mutate, label) { const element = parseSvg(source).elements.find(({name, ...rest}) => name === 'text' && predicate(rest)); assert.ok(element, `${label} fixture text`); const value = source.slice(element.openEnd, element.closeIndex); const changed = mutate(value); assert.notEqual(changed, value, `${label} mutation applies`); return `${source.slice(0, element.openEnd)}${changed}${source.slice(element.closeIndex)}`; }
function frontMatterFixture(metadata) { return Object.entries(metadata).flatMap(([key, value]) => Array.isArray(value) ? value.length ? [`${key}:`, ...value.map((item) => `  - ${item}`)] : [`${key}: []`] : [`${key}: ${value}`]).join('\n'); }
function removeFrontMatterField(source, key) { return source.replace(new RegExp(`^${escapeRegExp(key)}:.*(?:\\r?\\n  - [^\\r\\n]+)*(?:\\r?\\n|$)`, 'mu'), ''); }
function changeFrontMatterField(source, key) { const value = EXACT_METADATA[key]; return Array.isArray(value) && value.length ? replaceOnce(source, `  - ${value[0]}`, '  - changed', `${key} changed`) : replaceOnce(source, `${key}: ${Array.isArray(value) ? '[]' : value}`, `${key}: changed`, `${key} changed`); }
export function markdownTables(body) { const tables = []; const lines = body.split(/\r?\n/u); for (let index = 0; index < lines.length; index += 1) { if (!lines[index].startsWith('|')) continue; const rows = []; while (index < lines.length && lines[index].startsWith('|')) { rows.push(lines[index].slice(1, -1).split('|').map((cell) => cell.trim())); index += 1; } if (rows.length >= 3 && rows[1].every((cell) => /^:?-{3,}:?$/u.test(cell))) tables.push(rows); } return tables; }
function table(body, header) { const found = markdownTables(body).find((candidate) => JSON.stringify(candidate[0]) === JSON.stringify(header)); assert.ok(found, `table ${header.join(' | ')}`); return found; }
function exactRows(actual, expected, name) { assert.deepEqual(actual.slice(2), expected, `${name} exact ordered rows`); }
function section(source, heading) { const result = new RegExp(`(?:^|\\n)## ${escapeRegExp(heading)}\\n([\\s\\S]*?)(?=\\n## |$)`, 'u').exec(source)?.[1]; assert.ok(result, `${heading} section`); return result; }
function includesOrdered(source, values, label) { let at = -1; for (const value of values) { const next = source.indexOf(value, at + 1); assert.ok(next > at, `${label}: ${value}`); at = next; } }
function attributes(tag) { return new Map([...tag.matchAll(/([:\w-]+)\s*=\s*(?:"([^"]*)"|'([^']*)')/gu)].map(([, key, double, single]) => [key, double ?? single])); }
function decodeXmlText(value) { return value.replace(/&(?:#(\d+)|#x([\da-f]+)|amp|lt|gt|quot|apos);/giu, (entity, decimal, hex) => decimal ? String.fromCodePoint(Number(decimal)) : hex ? String.fromCodePoint(Number.parseInt(hex, 16)) : ({'&amp;': '&', '&lt;': '<', '&gt;': '>', '&quot;': '"', '&apos;': "'"})[entity] ?? entity); }
export function parseDrawio(source) { const cells = [...source.matchAll(/<mxCell\b[^>]*(?:\/>|>[\s\S]*?<\/mxCell>)/gu)].map(([raw]) => { const open = /^<mxCell\b[^>]*>/u.exec(raw)?.[0] ?? raw; const geometry = /<mxGeometry\b([^>]*)/u.exec(raw)?.[1] ?? ''; const array = /<Array\s+as="points"[^>]*>([\s\S]*?)<\/Array>/u.exec(raw); const points = array ? [...array[1].matchAll(/<mxPoint\b([^>]*)/gu)].map(([, point]) => attributes(`<mxPoint ${point}>`)) : []; return {raw, attributes: attributes(open), geometry: attributes(`<mxGeometry ${geometry}>`), points, hasPointsArray: Boolean(array), misplacedPoints: [...raw.matchAll(/<mxPoint\b/g)].length - points.length, label: decodeXmlText(attributes(open).get('value') ?? '')}; }); return {cells, nodes: cells.filter(({attributes: item}) => item.get('vertex') === '1'), edges: cells.filter(({attributes: item}) => item.get('edge') === '1')}; }
export function parseSvg(source) { const elements = []; const stack = []; for (const match of source.matchAll(/<\/?([A-Za-z][\w:.-]*)\b([^>]*)>/gu)) { const closing = match[0].startsWith('</'); if (closing) { const element = stack.pop(); assert.equal(element?.name, match[1], `balanced SVG element ${match[1]}`); element.closeIndex = match.index; continue; } const element = {name: match[1], attributes: attributes(match[2]), parent: stack.at(-1) ?? null, index: elements.length, sourceIndex: match.index, openEnd: match.index + match[0].length, closeIndex: match.index + match[0].length}; elements.push(element); if (!match[0].endsWith('/>')) stack.push(element); } assert.equal(stack.length, 0, 'balanced SVG tree'); return {elements, nodes: elements.filter(({attributes: item}) => item.has('data-node-id')), edges: elements.filter(({name, attributes: item}) => name === 'path' && item.has('data-edge-id'))}; }
function cssDeclarations(source = '') { const result = new Map(); for (const declaration of source.split(';').map((item) => item.trim()).filter(Boolean)) { const split = declaration.indexOf(':'); if (split < 0) continue; const property = declaration.slice(0, split).trim().toLowerCase(); const raw = declaration.slice(split + 1).trim(); result.set(property, {value: raw.replace(/\s*!important\s*$/iu, '').trim(), important: /\s*!important\s*$/iu.test(raw)}); } return result; }
function styleMap(value = '') { return new Map(value.split(';').filter(Boolean).map((item) => item.split(/=(.*)/su).map((part) => part.trim()))); }
function selectorSpecificity(selector) { return [(selector.match(/#[\w-]+/gu) ?? []).length, (selector.match(/\.[\w-]+|\[[^\]]+\]|:(?!:)[\w-]+/gu) ?? []).length, (selector.match(/(?:^|[\s>+~])([A-Za-z][\w-]*)/gu) ?? []).length]; }
function compareSpecificity(left, right) { return left[0] - right[0] || left[1] - right[1] || left[2] - right[2]; }
function styleRules(source) { const rules = []; let order = 0; for (const [, sheet] of source.matchAll(/<style\b[^>]*>([\s\S]*?)<\/style>/gu)) for (const [, selectors, declarations] of sheet.replace(/\/\*[\s\S]*?\*\//gu, '').matchAll(/([^{}]+)\{([^{}]*)\}/gu)) for (const selector of selectors.split(',').map((item) => item.trim()).filter(Boolean)) rules.push({selector, declarations: cssDeclarations(declarations), specificity: selectorSpecificity(selector), order: order++}); return rules; }
function simpleSelectorMatches(element, selector) { const simple = selector.trim(); if (!simple || /[+~>\s]/u.test(simple)) return false; if (simple.includes(':root') && element.parent) return false; const id = simple.match(/#([\w-]+)/u)?.[1]; const tag = simple.match(/^[A-Za-z][\w-]*/u)?.[0]; const classes = [...simple.matchAll(/\.([\w-]+)/gu)].map((match) => match[1]); const selectors = [...simple.matchAll(/\[([\w:-]+)(?:\s*=\s*["']?([^\]"']+)["']?)?\]/gu)]; return (!tag || element.name === tag) && (!id || element.attributes.get('id') === id) && classes.every((name) => (element.attributes.get('class') ?? '').split(/\s+/u).includes(name)) && selectors.every(([, key, value]) => element.attributes.has(key) && (value === undefined || element.attributes.get(key) === value.trim())); }
function selectorMatches(element, selector) { const parts = selector.trim().replace(/\s*>\s*/gu, ' > ').split(/\s+/u).filter(Boolean); let candidate = element; let cursor = parts.length - 1; if (!simpleSelectorMatches(candidate, parts[cursor])) return false; cursor -= 1; while (cursor >= 0) { if (parts[cursor] === '>') { candidate = candidate.parent; if (!candidate || cursor === 0 || !simpleSelectorMatches(candidate, parts[cursor - 1])) return false; cursor -= 2; } else { candidate = candidate.parent; while (candidate && !simpleSelectorMatches(candidate, parts[cursor])) candidate = candidate.parent; if (!candidate) return false; cursor -= 1; } } return true; }
function ownSvgPresentationValue(source, element, property) { let winner = element.attributes.has(property) ? {tier: 0, specificity: [0, 0, 0], order: -1, value: element.attributes.get(property)} : null; for (const rule of styleRules(source)) { const declaration = rule.declarations.get(property); if (!declaration || !selectorMatches(element, rule.selector)) continue; const candidate = {tier: declaration.important ? 3 : 1, specificity: rule.specificity, order: rule.order, value: declaration.value}; if (!winner || candidate.tier > winner.tier || candidate.tier === winner.tier && (compareSpecificity(candidate.specificity, winner.specificity) > 0 || compareSpecificity(candidate.specificity, winner.specificity) === 0 && candidate.order > winner.order)) winner = candidate; } const inline = cssDeclarations(element.attributes.get('style')).get(property); if (inline) { const candidate = {tier: inline.important ? 4 : 2, specificity: [1, 0, 0], order: Number.MAX_SAFE_INTEGER, value: inline.value}; if (!winner || candidate.tier >= winner.tier) winner = candidate; } return winner?.value; }
const INHERITED_SVG_PROPERTIES = new Set(['color', 'fill', 'fill-opacity', 'font-family', 'font-size', 'font-style', 'font-weight', 'marker-end', 'marker-mid', 'marker-start', 'stroke', 'stroke-dasharray', 'stroke-linecap', 'stroke-linejoin', 'stroke-opacity', 'stroke-width', 'text-anchor', 'visibility']);
export function svgPresentationValue(source, element, property) { const own = ownSvgPresentationValue(source, element, property); if (own !== undefined && !['inherit', 'unset'].includes(own)) return own === 'initial' ? undefined : own; if ((own === 'inherit' || own === 'unset' && INHERITED_SVG_PROPERTIES.has(property) || own === undefined && INHERITED_SVG_PROPERTIES.has(property)) && element.parent) return svgPresentationValue(source, element.parent, property); return undefined; }
function number(value, label) { const result = Number.parseFloat(value); assert.ok(Number.isFinite(result), label); return result; }
function numericBounds(attributesMap, label) { const result = Object.fromEntries(['x', 'y', 'width', 'height'].map((key) => [key, number(attributesMap.get(key), `${label} ${key}`)])); assert.ok(result.width >= 0 && result.height >= 0, `${label} nonnegative size`); return {...result, left: result.x, top: result.y, right: result.x + result.width, bottom: result.y + result.height}; }
export function assertFlattenedSvg(elements) { for (const element of elements) assert.equal(element.attributes.has('transform'), false, `flattened SVG geometry: <${element.name}> has no transform`); }
export function parsePathPoints(data) { assert.doesNotMatch(data ?? '', /[CQSAZ]/iu, 'connector path uses only M/L/H/V'); const tokens = data.match(/[A-Za-z]|-?(?:\d+(?:\.\d*)?|\.\d+)/gu) ?? []; const points = []; let cursor = 0; let command; let current = {x: 0, y: 0}; while (cursor < tokens.length) { if (/^[A-Za-z]$/u.test(tokens[cursor])) command = tokens[cursor++]; const relative = command === command?.toLowerCase(); const take = () => number(tokens[cursor++], 'path coordinate'); if (command?.toUpperCase() === 'M' || command?.toUpperCase() === 'L') { const x = take(); const y = take(); current = {x: relative ? current.x + x : x, y: relative ? current.y + y : y}; points.push(current); if (command?.toUpperCase() === 'M') command = relative ? 'l' : 'L'; } else if (command?.toUpperCase() === 'H') { const x = take(); current = {x: relative ? current.x + x : x, y: current.y}; points.push(current); } else if (command?.toUpperCase() === 'V') { const y = take(); current = {x: current.x, y: relative ? current.y + y : y}; points.push(current); } else assert.fail(`unsupported path command ${command}`); } assert.ok(points.length >= 2, 'visible connector path'); return points; }
function shapeBounds(element) { if (element.name === 'rect') return numericBounds(element.attributes, 'rect'); if (element.name === 'circle' || element.name === 'ellipse') { const cx = number(element.attributes.get('cx'), 'shape cx'); const cy = number(element.attributes.get('cy'), 'shape cy'); const rx = number(element.attributes.get(element.name === 'circle' ? 'r' : 'rx'), 'shape rx'); const ry = element.name === 'circle' ? rx : number(element.attributes.get('ry'), 'shape ry'); return {left: cx - rx, right: cx + rx, top: cy - ry, bottom: cy + ry}; } if (element.name === 'path') { const points = parsePathPoints(element.attributes.get('d')); return {left: Math.min(...points.map(({x}) => x)), right: Math.max(...points.map(({x}) => x)), top: Math.min(...points.map(({y}) => y)), bottom: Math.max(...points.map(({y}) => y))}; } assert.fail(`unsupported visible shape ${element.name}`); }
function terminalPoint(node, edge, side) { const box = numericBounds(node.geometry, node.attributes.get('id')); const style = styleMap(edge.attributes.get('style')); for (const key of [`${side}X`, `${side}Y`, `${side}Dx`, `${side}Dy`, `${side}Perimeter`]) assert.ok(style.has(key), `${edge.attributes.get('id')} ${key}`); assert.equal(style.get(`${side}Dx`), '0', 'terminal dx'); assert.equal(style.get(`${side}Dy`), '0', 'terminal dy'); assert.equal(style.get(`${side}Perimeter`), '1', 'terminal perimeter'); const x = number(style.get(`${side}X`), 'normalized terminal x'); const y = number(style.get(`${side}Y`), 'normalized terminal y'); assert.ok(x >= 0 && x <= 1 && y >= 0 && y <= 1 && (x === 0 || x === 1 || y === 0 || y === 1), 'normalized terminal on perimeter'); return {x: box.x + box.width * x, y: box.y + box.height * y}; }
export function drawioRoute(edge, nodeById) { const source = nodeById.get(edge.attributes.get('source')); const target = nodeById.get(edge.attributes.get('target')); assert.ok(source && target, `${edge.attributes.get('id')} real terminals`); assert.ok(edge.hasPointsArray, `${edge.attributes.get('id')} waypoint array`); assert.equal(edge.misplacedPoints, 0, `${edge.attributes.get('id')} points only in waypoint array`); assert.equal(edge.points.some((point) => ['sourcePoint', 'targetPoint'].includes(point.get('as'))), false, `${edge.attributes.get('id')} no fallback points`); return [terminalPoint(source, edge, 'exit'), ...edge.points.map((point) => ({x: number(point.get('x'), 'waypoint x'), y: number(point.get('y'), 'waypoint y')})), terminalPoint(target, edge, 'entry')]; }
export function glyphBox({x, y, text, fontSize, anchor = 'start'}) { const width = [...text].reduce((total, character) => total + (/^[\u0000-\u00ff]$/u.test(character) ? .64 : 1), 0) * fontSize; const left = anchor === 'middle' ? x - width / 2 : anchor === 'end' ? x - width : x; return {left, right: left + width, top: y - fontSize * .82, bottom: y + fontSize * .22}; }
export function alphaCompose(backdrop, foreground) { const alpha = foreground.alpha + backdrop.alpha * (1 - foreground.alpha); if (alpha === 0) return {red: 0, green: 0, blue: 0, alpha: 0}; return {red: (foreground.red * foreground.alpha + backdrop.red * backdrop.alpha * (1 - foreground.alpha)) / alpha, green: (foreground.green * foreground.alpha + backdrop.green * backdrop.alpha * (1 - foreground.alpha)) / alpha, blue: (foreground.blue * foreground.alpha + backdrop.blue * backdrop.alpha * (1 - foreground.alpha)) / alpha, alpha}; }
export function markerEnvelope(endpoint, previous, {width, height, refX, refY, viewBox = [0, 0, width, height], pathBounds = {left: viewBox[0], top: viewBox[1], right: viewBox[0] + viewBox[2], bottom: viewBox[1] + viewBox[3]}, preserveAspectRatio = 'xMidYMid meet'}) { const dx = endpoint.x - previous.x; const dy = endpoint.y - previous.y; const length = Math.hypot(dx, dy); assert.ok(length > 0, 'marker terminal direction'); const [, , viewWidth, viewHeight] = viewBox; assert.ok(viewWidth > 0 && viewHeight > 0 && width > 0 && height > 0, 'positive marker viewport and viewBox'); const unit = {x: dx / length, y: dy / length}; const normal = {x: -unit.y, y: unit.x}; const [scaleX, scaleY] = preserveAspectRatio === 'none' ? [width / viewWidth, height / viewHeight] : (assert.equal(preserveAspectRatio, 'xMidYMid meet', 'supported marker preserveAspectRatio'), close(width / viewWidth, height / viewHeight, 'meet marker aspect ratio'), [width / viewWidth, height / viewHeight]); const points = [[pathBounds.left, pathBounds.top], [pathBounds.right, pathBounds.top], [pathBounds.right, pathBounds.bottom], [pathBounds.left, pathBounds.bottom]].map(([x, y]) => ({x: endpoint.x + unit.x * (x - refX) * scaleX + normal.x * (y - refY) * scaleY, y: endpoint.y + unit.y * (x - refX) * scaleX + normal.y * (y - refY) * scaleY})); return {left: Math.min(...points.map(({x}) => x)), right: Math.max(...points.map(({x}) => x)), top: Math.min(...points.map(({y}) => y)), bottom: Math.max(...points.map(({y}) => y))}; }
function overlaps(left, right) { return left.left < right.right && left.right > right.left && left.top < right.bottom && left.bottom > right.top; }
export function assertNoLaterPaintMask(route, masks) { for (const mask of masks) assert.equal(mask.alpha > 0 && routeBoxDistance(route, mask) === 0, false, 'later paint does not mask a semantic route'); }
function close(left, right, label) { assert.ok(Math.abs(left - right) < .01, `${label}: ${left} !== ${right}`); }
function equalRoute(actual, expected, label) { assert.equal(actual.length, expected.length, `${label} point count`); actual.forEach((point, index) => { close(point.x, expected[index].x, `${label}[${index}].x`); close(point.y, expected[index].y, `${label}[${index}].y`); }); }
function routeDistance(point, start, end) { const dx = end.x - start.x; const dy = end.y - start.y; const length = dx * dx + dy * dy; if (length === 0) return Math.hypot(point.x - start.x, point.y - start.y); const ratio = Math.max(0, Math.min(1, ((point.x - start.x) * dx + (point.y - start.y) * dy) / length)); return Math.hypot(point.x - start.x - ratio * dx, point.y - start.y - ratio * dy); }
function pointInBox(point, box) { return point.x >= box.left && point.x <= box.right && point.y >= box.top && point.y <= box.bottom; }
function segmentsCross(a, b, c, d) { const cross = (p, q, r) => (q.x - p.x) * (r.y - p.y) - (q.y - p.y) * (r.x - p.x); const onSegment = (p, q, r) => Math.abs(cross(p, q, r)) < 1e-9 && r.x >= Math.min(p.x, q.x) - 1e-9 && r.x <= Math.max(p.x, q.x) + 1e-9 && r.y >= Math.min(p.y, q.y) - 1e-9 && r.y <= Math.max(p.y, q.y) + 1e-9; const first = cross(a, b, c); const second = cross(a, b, d); const third = cross(c, d, a); const fourth = cross(c, d, b); return (first > 0 && second < 0 || first < 0 && second > 0) && (third > 0 && fourth < 0 || third < 0 && fourth > 0) || onSegment(a, b, c) || onSegment(a, b, d) || onSegment(c, d, a) || onSegment(c, d, b); }
function segmentBoxDistance(start, end, box) { if (pointInBox(start, box) || pointInBox(end, box)) return 0; const corners = [{x: box.left, y: box.top}, {x: box.right, y: box.top}, {x: box.right, y: box.bottom}, {x: box.left, y: box.bottom}]; const edges = corners.map((point, index) => [point, corners[(index + 1) % corners.length]]); if (edges.some(([left, right]) => segmentsCross(start, end, left, right))) return 0; return Math.min(...corners.map((point) => routeDistance(point, start, end)), ...edges.flatMap(([left, right]) => [routeDistance(start, left, right), routeDistance(end, left, right)])); }
function routeBoxDistance(points, box) { return Math.min(...points.slice(1).map((point, index) => segmentBoxDistance(points[index], point, box))); }
function assertRouteGlyphClearance(route, glyph, label) { assert.ok(routeBoxDistance(route, glyph) >= 24, `${label} 8 CSS-pixel visible-glyph-to-stroke clearance`); }
function boxDistance(left, right) { return Math.hypot(Math.max(left.left - right.right, right.left - left.right, 0), Math.max(left.top - right.bottom, right.top - left.bottom, 0)); }
function assertGlyphInBoundary(glyph, boundary, label, horizontal = 48, vertical = 42, strokeHalf = 1.5) { assert.ok(glyph.left - (boundary.left + strokeHalf) >= horizontal, `${label} left boundary clearance`); assert.ok((boundary.right - strokeHalf) - glyph.right >= horizontal, `${label} right boundary clearance`); assert.ok(glyph.top - (boundary.top + strokeHalf) >= vertical, `${label} top boundary clearance`); assert.ok((boundary.bottom - strokeHalf) - glyph.bottom >= vertical, `${label} bottom boundary clearance`); }
function samePoint(left, right) { return Math.abs(left.x - right.x) < 1e-9 && Math.abs(left.y - right.y) < 1e-9; }
function partialCollinearOverlap(a, b, c, d) { const cross = (p, q, r) => (q.x - p.x) * (r.y - p.y) - (q.y - p.y) * (r.x - p.x); if (Math.abs(cross(a, b, c)) > 1e-9 || Math.abs(cross(a, b, d)) > 1e-9) return false; const axis = Math.abs(b.x - a.x) >= Math.abs(b.y - a.y) ? 'x' : 'y'; const first = [a[axis], b[axis]].sort((left, right) => left - right); const second = [c[axis], d[axis]].sort((left, right) => left - right); return Math.min(first[1], second[1]) - Math.max(first[0], second[0]) > 1e-9; }
function exactSharedTerminalContact(left, right, a, b, c, d) { const candidates = [[left.source, left.points[0]], [left.target, left.points.at(-1)]].flatMap(([id, point]) => [[id, point]]); return candidates.some(([id, point]) => [[right.source, right.points[0]], [right.target, right.points.at(-1)]].some(([otherId, otherPoint]) => id === otherId && samePoint(point, otherPoint) && [a, b].some((candidate) => samePoint(candidate, point)) && [c, d].some((candidate) => samePoint(candidate, point)))); }
function elementText(source, element) { return decodeXmlText(source.slice(element.openEnd, element.closeIndex).replace(/<[^>]+>/gu, '')).trim(); }
function descendant(parent, child) { for (let item = child.parent; item; item = item.parent) if (item === parent) return true; return false; }
function svgBoundsFor(owner, elements) { const shape = elements.find((element) => descendant(owner, element) && ['rect', 'circle', 'ellipse'].includes(element.name)); assert.ok(shape, `${owner.attributes.get('data-node-id') ?? owner.attributes.get('data-region-id')} visible shape`); return shapeBounds(shape); }
function markerPathBounds(marker, elements, markerId) { const paths = elements.filter((element) => descendant(marker, element) && element.name === 'path'); assert.equal(paths.length, 1, `${markerId} one visible marker path`); const shape = paths[0]; assert.equal(shape.attributes.get('transform') ?? '', '', `${markerId} marker path transform`); const data = shape.attributes.get('d') ?? ''; assert.doesNotMatch(data, /[CQSA]/iu, `${markerId} marker path is linear`); const points = parsePathPoints(data.replace(/[Zz]/gu, '')); return {left: Math.min(...points.map(({x}) => x)), right: Math.max(...points.map(({x}) => x)), top: Math.min(...points.map(({y}) => y)), bottom: Math.max(...points.map(({y}) => y))}; }
function markerBounds(svgSource, elements, path, points) { const markerId = svgPresentationValue(svgSource, path, 'marker-end')?.match(/^url\(#([^)]+)\)$/u)?.[1]; assert.ok(markerId, `${path.attributes.get('data-edge-id') ?? path.attributes.get('data-legend-edge-id')} marker`); const marker = elements.find(({name, attributes: item}) => name === 'marker' && item.get('id') === markerId); assert.ok(marker, `${markerId} definition`); assert.equal(marker.attributes.get('markerUnits'), 'userSpaceOnUse', `${markerId} markerUnits`); assert.equal(marker.attributes.get('transform') ?? '', '', `${markerId} marker transform`); const viewBox = (marker.attributes.get('viewBox') ?? '').trim().split(/[\s,]+/u).filter(Boolean).map(Number); assert.equal(viewBox.length, 4, `${markerId} viewBox arity`); assert.ok(viewBox.every(Number.isFinite) && viewBox[2] > 0 && viewBox[3] > 0, `${markerId} positive viewBox`); const width = number(marker.attributes.get('markerWidth'), `${markerId} marker width`); const height = number(marker.attributes.get('markerHeight'), `${markerId} marker height`); const refX = number(marker.attributes.get('refX'), `${markerId} marker refX`); const refY = number(marker.attributes.get('refY'), `${markerId} marker refY`); const preserveAspectRatio = marker.attributes.get('preserveAspectRatio') ?? 'xMidYMid meet'; assert.ok(['none', 'xMidYMid meet'].includes(preserveAspectRatio), `${markerId} supported preserveAspectRatio`); assert.ok(refX >= viewBox[0] && refX <= viewBox[0] + viewBox[2] && refY >= viewBox[1] && refY <= viewBox[1] + viewBox[3], `${markerId} marker reference lies in viewBox`); assert.equal(marker.attributes.get('orient'), 'auto', `${markerId} marker orient`); const pathBounds = markerPathBounds(marker, elements, markerId); assert.ok(pathBounds.left >= viewBox[0] && pathBounds.right <= viewBox[0] + viewBox[2] && pathBounds.top >= viewBox[1] && pathBounds.bottom <= viewBox[1] + viewBox[3], `${markerId} marker path fits viewBox`); return markerEnvelope(points.at(-1), points.at(-2), {width, height, refX, refY, viewBox, pathBounds, preserveAspectRatio}); }
function semanticRole(cell) { const role = styleMap(cell.attributes.get('style')).get('semanticRole'); assert.ok(role, `${cell.attributes.get('id')} semantic role`); return role; }
function assertServerlessArticle(source) {
  assert.deepEqual(parseFrontMatter(source), EXACT_METADATA, 'exact STY-11 front matter');
  const headings = findMarkdownHeadings(source);
  assert.deepEqual(headings.filter(({level}) => level === 2).map(({text}) => text), EXPECTED_HEADINGS, 'exact H2 order');
  const migration = headings.find(({level, text}) => level === 2 && text === '可迁移经验');
  const next = headings.find(({level, offset}) => level === 2 && offset > migration.offset);
  assert.deepEqual(headings.filter(({level, offset}) => level === 3 && offset > migration.offset && (!next || offset < next.offset)).map(({text}) => text), MIGRATION_HEADINGS, 'exact migration H3 order');
  for (const label of WRAPPERS) assert.match(source, new RegExp('<div\\b(?=[^>]*role="region")(?=[^>]*aria-label="' + escapeRegExp(label) + '")(?=[^>]*tabIndex=\\{0\\})(?=[^>]*onKeyDown=\\{handleHorizontalArrowKey\\})[^>]*>', 'u'), label + ' keyboard scroll wrapper');
  assert.equal((source.match(/role="region"/gu) ?? []).length, 4, 'exactly four wrappers');
  assert.deepEqual(table(source, ['构件', '正向责任', '持久事实', '明确不拥有']).slice(2), OWNERSHIP_ROWS, 'exact ownership table');
  assert.deepEqual(table(source, ['故障', '检测', '自动响应', '停止条件', '最终责任人']).slice(2), FAILURE_ROWS, 'exact failure table');
  assert.deepEqual(table(source, ['观察', '先验证', '首选动作', '升级条件']).slice(2), COLD_COST_ROWS, 'exact cold-start/cost table');
  includesOrdered(source, ORDER_FLOW, 'nine-step order flow'); includesOrdered(source, CONCURRENCY_LAYERS, 'three concurrency budgets');
  for (const [identity, meaning] of IDENTITY_SEMANTICS) assert.match(source, new RegExp(escapeRegExp(identity) + '[^。；\n]*' + escapeRegExp(meaning), 'u'), identity + ' has distinct visible semantics');
  assert.equal(new Set(IDENTITY_SEMANTICS.map(([, meaning]) => meaning)).size, IDENTITY_SEMANTICS.length, 'identity semantics are distinct');
  includesOrdered(source, ['必须保持可导出', '可以合理适配', '可以明确绑定'], 'vendor boundaries');
  includesOrdered(source, ['导出当前订单状态与未完成操作', '冻结新流程版本', '暂停或排空旧消费者', '迁移事件合同、幂等身份和外部回执', '在新执行面恢复未完成步骤', '验证旧事件或迟到结果不会覆盖新状态', '撤销旧触发器、凭证和写权限'], 'exit drill');
  for (const signal of APPLICABILITY_SIGNALS) assert.match(source, new RegExp(escapeRegExp(signal), 'u'), 'Serverless applicability: ' + signal);
  for (const condition of STOP_ADOPTION_CONDITIONS) assert.match(source, new RegExp(escapeRegExp(condition), 'u'), 'stop-adoption condition: ' + condition);
  for (const unsafe of ['函数内存作为业务状态', '同步等待整条履约链', '队列就是成功', '事件标识就是业务幂等', '盲目重放', '函数扩容决定库存', '缺少条件状态转移', '下游预算高于权威容量', '无限重试不受限制', '关键步骤失败开放', '通知回滚已确认订单', '毒消息重试', '默认预热', '只比较价格', '人工负责人待定', 'CloudEvents意味着投递', '工作流 DSL 意味着运行时等价', '强制可移植适配', '只迁移函数']) assert.doesNotMatch(source, new RegExp(escapeRegExp(unsafe), 'u'), unsafe + ' is rejected');
}

function assertServerlessSources(ledger) {
  const document = ledger.documents?.[ARTICLE];
  assert.ok(document, 'STY-11 governed source document');
  assert.deepEqual(document.citations.map(({source_id}) => source_id), SOURCE_IDS, 'exact ordered source citations');
  assert.equal(document.citations.filter(({source_id}) => source_id !== SOURCE_IDS.at(-1)).length, 10, 'exactly ten remote citations');
  assert.deepEqual(document.citations.filter(({manifest_primary}) => manifest_primary).map(({source_id}) => source_id), ['src-cncf-serverless-whitepaper-v1'], 'whitepaper is sole primary');
  for (const [id, expected] of Object.entries(REMOTE_SOURCES)) {
    const source = ledger.sources.find((item) => item.id === id); const citation = document.citations.find((item) => item.source_id === id); assert.ok(source && citation, id + ' record and citation');
    assert.deepEqual({canonical_locator: source.canonical_locator, transport_locator: source.transport_locator, expected_final_transport_locator: source.expected_final_transport_locator, version: source.version, license: source.license, copyright_policy: source.copyright_policy, allowed_evidence_roles: source.allowed_evidence_roles, usage_boundary: source.usage_boundary}, {canonical_locator: expected.canonical_locator, transport_locator: expected.transport_locator, expected_final_transport_locator: expected.transport_locator, version: expected.version, license: expected.license, copyright_policy: expected.copyright_policy, allowed_evidence_roles: expected.roles, usage_boundary: expected.usage_boundary}, id + ' exact source governance');
    assert.deepEqual(citation.roles, expected.roles, id + ' used evidence role'); assert.equal(citation.usage_mode, 'facts-summary', id + ' conservative facts-summary');
  }
  const source = ledger.sources.find((item) => item.id === SOURCE_IDS.at(-1)); const citation = document.citations.find((item) => item.source_id === SOURCE_IDS.at(-1)); assert.ok(source && citation, 'original illustration record and citation');
  assert.deepEqual({canonical_locator: source.canonical_locator, transport_locator: source.transport_locator, expected_final_transport_locator: source.expected_final_transport_locator, version: source.version, license: source.license, copyright_policy: source.copyright_policy, allowed_evidence_roles: source.allowed_evidence_roles, usage_boundary: source.usage_boundary}, {canonical_locator: ORIGINAL_SOURCE.canonical_locator, transport_locator: ORIGINAL_SOURCE.transport_locator, expected_final_transport_locator: ORIGINAL_SOURCE.transport_locator, version: ORIGINAL_SOURCE.version, license: ORIGINAL_SOURCE.license, copyright_policy: ORIGINAL_SOURCE.copyright_policy, allowed_evidence_roles: ORIGINAL_SOURCE.roles, usage_boundary: ORIGINAL_SOURCE.usage_boundary}, 'original illustration rights fields');
  assert.deepEqual(citation.roles, ORIGINAL_SOURCE.roles, 'original illustration role'); assert.equal(citation.usage_mode, 'original-illustration', 'original illustration usage');
}

async function assertServerlessRelationsAndStageA() {
  const documents = await readContentDocuments(CONTENT_ROOT);
  const article = documents.find(({file}) => 'content/' + file === ARTICLE);
  assert.ok(article, 'STY-11 content document');
  const links = extractInternalLinks(article);
  assert.ok(links.includes(RELATED_CASE), 'visible related case link');
  assert.equal(links.includes('/styles/sty-12'), false, 'STY-12 remains non-actionable');
  for (const path of ['content/styles/sty-06-event-driven-architecture.mdx', 'content/styles/sty-09-pipes-and-filters.mdx', 'content/cases/cloudflare-durable-objects-workerd.mdx']) {
    const target = documents.find(({file}) => 'content/' + file === path);
    assert.ok(target, path + ' exists');
    assert.ok(extractInternalLinks(target).includes(ROUTE), path + ' visibly reciprocates STY-11');
  }
  const status = JSON.parse(readFileSync('src/generated/project-status.json', 'utf8'));
  assert.deepEqual({completed: status.completed_topics, documents: status.content_documents, sources: status.governed_sources}, EXPECTED_STAGE_A, 'exact Stage A projection');
}

function assertServerlessDiagram(drawioSource, svgSource) {
  const drawio = parseDrawio(drawioSource);
  const nodes = new Map(drawio.nodes.map((node) => [node.attributes.get('id'), node]));
  const edges = new Map(drawio.edges.map((edge) => [edge.attributes.get('id'), edge]));
  const svg = parseSvg(svgSource); assertFlattenedSvg(svg.elements);
  const root = svg.elements.find(({name}) => name === 'svg');
  assert.deepEqual((root?.attributes.get('viewBox') ?? '').split(/\s+/u).map(Number), [0, 0, 2400, 3600], '2400x3600 source canvas renders at 800x1200 CSS pixels');
  for (const id of REGION_IDS) {
    const cell = nodes.get(id); const rendered = svg.elements.find(({attributes}) => attributes.get('data-region-id') === id);
    assert.ok(cell && rendered, id + ' Draw.io/SVG region pair'); assert.equal(semanticRole(cell), 'region', id + ' semantic region');
    const left = numericBounds(cell.geometry, id); const right = svgBoundsFor(rendered, svg.elements);
    for (const key of ['left', 'top', 'right', 'bottom']) close(left[key], right[key], id + ' region bounds');
  }
  const nodeBounds = new Map();
  for (const id of NODE_IDS) {
    const cell = nodes.get('node-' + id); const rendered = svg.nodes.find(({attributes}) => attributes.get('data-node-id') === id);
    assert.ok(cell && rendered, id + ' Draw.io/SVG node pair'); assert.equal(semanticRole(cell), 'node-shape', id + ' semantic node');
    const left = numericBounds(cell.geometry, id); const right = svgBoundsFor(rendered, svg.elements);
    for (const key of ['left', 'top', 'right', 'bottom']) close(left[key], right[key], id + ' node bounds');
    const title = svg.elements.find(({name, attributes}) => name === 'text' && attributes.get('data-header-for') === 'node-' + id);
    const type = svg.elements.find(({name, attributes}) => name === 'text' && attributes.get('data-type-for') === 'node-' + id);
    assert.ok(title && type, id + ' title/type labels');
    const titleFont = number(svgPresentationValue(svgSource, title, 'font-size'), id + ' title font'); const typeFont = number(svgPresentationValue(svgSource, type, 'font-size'), id + ' type font');
    assert.ok(titleFont >= 45 && typeFont >= 45, id + ' body/title/type text is at least 15 CSS pixels');
    const titleBox = glyphBox({x: number(title.attributes.get('x'), id + ' title x'), y: number(title.attributes.get('y'), id + ' title y'), text: elementText(svgSource, title), fontSize: titleFont, anchor: svgPresentationValue(svgSource, title, 'text-anchor') ?? 'start'});
    const typeBox = glyphBox({x: number(type.attributes.get('x'), id + ' type x'), y: number(type.attributes.get('y'), id + ' type y'), text: elementText(svgSource, type), fontSize: typeFont, anchor: svgPresentationValue(svgSource, type, 'text-anchor') ?? 'start'});
    assert.ok(titleBox.left - left.left >= 48 && left.right - titleBox.right >= 48 && typeBox.left - left.left >= 48 && left.right - typeBox.right >= 48 && titleBox.top - left.top >= 42 && typeBox.top - titleBox.bottom >= 66 && left.bottom - typeBox.bottom >= 42, id + ' 16/14 padding and 22px baseline');
    nodeBounds.set(id, left);
  }
  const routes = [];
  for (const id of EDGE_IDS) {
    const [source, target, role] = EDGE_CONTRACTS[id]; const edge = edges.get(id); const rendered = svg.edges.find(({attributes}) => attributes.get('data-edge-id') === id);
    assert.ok(edge && rendered, id + ' Draw.io/SVG edge pair'); assert.equal(edge.attributes.get('source'), 'node-' + source, id + ' source'); assert.equal(edge.attributes.get('target'), 'node-' + target, id + ' target'); assert.equal(semanticRole(edge), role, id + ' Draw.io role'); assert.equal(rendered.attributes.get('data-edge-role'), role, id + ' SVG role');
    const route = drawioRoute(edge, nodes); const svgRoute = parsePathPoints(rendered.attributes.get('d')); equalRoute(svgRoute, route, id + ' route');
    const style = styleMap(edge.attributes.get('style')); assert.equal(svgPresentationValue(svgSource, rendered, 'stroke'), style.get('strokeColor'), id + ' effective stroke'); close(number(svgPresentationValue(svgSource, rendered, 'stroke-width'), id + ' SVG width'), number(style.get('strokeWidth'), id + ' Draw.io width'), id + ' line width'); assert.equal(svgPresentationValue(svgSource, rendered, 'stroke-dasharray') ?? '', style.get('dashPattern') || '', id + ' dash');
    const marker = markerBounds(svgSource, svg.elements, rendered, svgRoute); const label = svg.elements.find(({name, attributes}) => name === 'text' && attributes.get('data-edge-id') === id); assert.ok(label, id + ' edge label');
    const labelBox = glyphBox({x: number(label.attributes.get('x'), id + ' label x'), y: number(label.attributes.get('y'), id + ' label y'), text: elementText(svgSource, label), fontSize: number(svgPresentationValue(svgSource, label, 'font-size'), id + ' edge font'), anchor: svgPresentationValue(svgSource, label, 'text-anchor') ?? 'start'});
    assert.ok(number(svgPresentationValue(svgSource, label, 'font-size'), id + ' edge font') >= 45, id + ' 15px edge text'); assertRouteGlyphClearance(svgRoute, labelBox, id); assert.ok(boxDistance(labelBox, marker) >= 48, id + ' 16px arrow clearance');
    for (const [foreign, box] of nodeBounds) if (foreign !== source && foreign !== target) { assert.ok(routeBoxDistance(svgRoute, box) >= 36 && boxDistance(labelBox, box) >= 36, id + ' 12px foreign-node clearance'); assert.equal(overlaps(marker, box), false, id + ' marker footprint'); }
    routes.push({id, source: 'node-' + source, target: 'node-' + target, points: svgRoute, rendered});
  }
  for (const role of LEGEND_ROLES) {
    const edge = edges.get('legend-edge-' + role); const rendered = svg.elements.find(({name, attributes}) => name === 'path' && attributes.get('data-legend-edge-id') === 'legend-edge-' + role); const label = svg.elements.find(({name, attributes}) => name === 'text' && attributes.get('data-legend-label-for') === 'legend-edge-' + role);
    assert.ok(edge && rendered && label, role + ' complete legend pair'); assert.equal(styleMap(edge.attributes.get('style')).get('legendRole'), role, role + ' Draw.io legend role'); assert.equal(rendered.attributes.get('data-edge-role'), role, role + ' SVG legend role');
    const legendRoute = drawioRoute(edge, nodes); const svgRoute = parsePathPoints(rendered.attributes.get('d')); equalRoute(svgRoute, legendRoute, role + ' legend route');
    const style = styleMap(edge.attributes.get('style')); assert.equal(svgPresentationValue(svgSource, rendered, 'stroke'), style.get('strokeColor'), role + ' effective legend stroke'); close(number(svgPresentationValue(svgSource, rendered, 'stroke-width'), role + ' legend SVG width'), number(style.get('strokeWidth'), role + ' legend Draw.io width'), role + ' legend width'); assert.equal(svgPresentationValue(svgSource, rendered, 'stroke-dasharray') ?? '', style.get('dashPattern') || '', role + ' legend dash');
    const marker = markerBounds(svgSource, svg.elements, rendered, svgRoute); const font = number(svgPresentationValue(svgSource, label, 'font-size'), role + ' legend label font'); assert.ok(font >= 45, role + ' legend 15px text'); const labelBox = glyphBox({x: number(label.attributes.get('x'), role + ' legend label x'), y: number(label.attributes.get('y'), role + ' legend label y'), text: elementText(svgSource, label), fontSize: font, anchor: svgPresentationValue(svgSource, label, 'text-anchor') ?? 'start'}); assertRouteGlyphClearance(svgRoute, labelBox, role + ' legend'); assert.ok(boxDistance(labelBox, marker) >= 48, role + ' legend label-to-arrow clearance');
    routes.push({id: 'legend-edge-' + role, source: edge.attributes.get('source'), target: edge.attributes.get('target'), points: svgRoute, rendered});
  }
  for (let left = 0; left < routes.length; left += 1) for (let right = left + 1; right < routes.length; right += 1) for (let a = 1; a < routes[left].points.length; a += 1) for (let b = 1; b < routes[right].points.length; b += 1) { const first = routes[left].points[a - 1]; const second = routes[left].points[a]; const third = routes[right].points[b - 1]; const fourth = routes[right].points[b]; assert.equal(partialCollinearOverlap(first, second, third, fourth), false, 'no partial collinear overlap'); if (segmentsCross(first, second, third, fourth)) assert.equal(exactSharedTerminalContact(routes[left], routes[right], first, second, third, fourth), true, 'only shared terminals intersect'); }
  for (const route of routes) { const masks = svg.elements.filter((element) => element.index > route.rendered.index && ['rect', 'circle', 'ellipse', 'path'].includes(element.name) && svgPresentationValue(svgSource, element, 'fill') !== 'none').map((element) => ({...shapeBounds(element), alpha: number(svgPresentationValue(svgSource, element, 'fill-opacity') ?? 1, 'mask alpha')})); assertNoLaterPaintMask(route.points, masks); }
}

function fixtureArticle() {
  const front = frontMatterFixture(EXACT_METADATA);
  const sections = EXPECTED_HEADINGS.map((heading) => '## ' + heading + (heading === '可迁移经验' ? '\n### ' + MIGRATION_HEADINGS.join('\n### ') : '')).join('\n');
  const wrappers = WRAPPERS.map((label) => exactWrapper(label)).join('\n');
  const ownership = OWNERSHIP_ROWS.map((row) => '| ' + row.join(' | ') + ' |').join('\n');
  const failures = FAILURE_ROWS.map((row) => '| ' + row.join(' | ') + ' |').join('\n');
  const cost = COLD_COST_ROWS.map((row) => '| ' + row.join(' | ') + ' |').join('\n');
  return '---\n' + front + '\n---\n' + sections + '\n' + wrappers + '\n| 构件 | 正向责任 | 持久事实 | 明确不拥有 |\n| --- | --- | --- | --- |\n' + ownership + '\n' + ORDER_FLOW.join('\n') + '\n' + CONCURRENCY_LAYERS.join('\n') + '\n' + IDENTITY_SEMANTICS.map(([identity, meaning]) => identity + meaning).join('。') + '。\n| 故障 | 检测 | 自动响应 | 停止条件 | 最终责任人 |\n| --- | --- | --- | --- | --- |\n' + failures + '\n\n| 观察 | 先验证 | 首选动作 | 升级条件 |\n| --- | --- | --- | --- |\n' + cost + '\n必须保持可导出\n可以合理适配\n可以明确绑定\n导出当前订单状态与未完成操作\n冻结新流程版本\n暂停或排空旧消费者\n迁移事件合同、幂等身份和外部回执\n在新执行面恢复未完成步骤\n验证旧事件或迟到结果不会覆盖新状态\n撤销旧触发器、凭证和写权限\n' + APPLICABILITY_SIGNALS.join('、') + '。\n' + STOP_ADOPTION_CONDITIONS.join('；') + '。';
}

test('STY-11 helper and mutation fixtures lock the approved content contract', () => {
  const fixture = fixtureArticle(); assertServerlessArticle(fixture);
  for (const key of Object.keys(EXACT_METADATA)) { assert.throws(() => assertServerlessArticle(removeFrontMatterField(fixture, key)), assert.AssertionError, key + ' deletion rejected'); assert.throws(() => assertServerlessArticle(changeFrontMatterField(fixture, key)), assert.AssertionError, key + ' changed rejected'); }
  for (const heading of [...EXPECTED_HEADINGS, ...MIGRATION_HEADINGS]) { const token = (MIGRATION_HEADINGS.includes(heading) ? '### ' : '## ') + heading; assert.throws(() => assertServerlessArticle(replaceOnce(fixture, token, '', heading)), assert.AssertionError, heading + ' deletion rejected'); assert.throws(() => assertServerlessArticle(replaceOnce(fixture, token, token + '（变更）', heading)), assert.AssertionError, heading + ' changed rejected'); }
  for (const label of WRAPPERS) {
    const tag = exactWrapper(label);
    for (const [from, to] of [['role="region"', 'role="table"'], ['aria-label="' + label + '"', 'aria-label="' + label + '（变更）"'], ['tabIndex={0}', 'tabIndex={-1}'], ['onKeyDown={handleHorizontalArrowKey}', 'onKeyDown={undefined}']]) {
      assert.throws(() => assertServerlessArticle(replaceOnce(fixture, tag, tag.replace(from, ''), label + ' ' + from + ' deletion')), assert.AssertionError, label + ' own wrapper deletion rejected');
      assert.throws(() => assertServerlessArticle(replaceOnce(fixture, tag, tag.replace(from, to), label + ' ' + from + ' change')), assert.AssertionError, label + ' own wrapper change rejected');
    }
  }
  for (const rows of [OWNERSHIP_ROWS, FAILURE_ROWS, COLD_COST_ROWS]) for (const row of rows) for (let index = 0; index < row.length; index += 1) {
    const deleted = [...row]; deleted[index] = ''; const changed = [...row]; changed[index] = '错误的合同值'; const exact = '| ' + row.join(' | ') + ' |';
    assert.throws(() => assertServerlessArticle(replaceOnce(fixture, exact, '| ' + deleted.join(' | ') + ' |', row[0] + ' deletion')), assert.AssertionError, row[0] + ' cell deletion rejected');
    assert.throws(() => assertServerlessArticle(replaceOnce(fixture, exact, '| ' + changed.join(' | ') + ' |', row[0] + ' change')), assert.AssertionError, row[0] + ' cell changed-value rejected');
  }
  for (const unsafe of ['函数内存作为业务状态', '同步等待整条履约链', '队列就是成功', '事件标识就是业务幂等', '盲目重放', '函数扩容决定库存', '缺少条件状态转移', '下游预算高于权威容量', '无限重试不受限制', '关键步骤失败开放', '通知回滚已确认订单', '毒消息重试', '默认预热', '只比较价格', '人工负责人待定', 'CloudEvents意味着投递', '工作流 DSL 意味着运行时等价', '强制可移植适配', '只迁移函数']) assert.throws(() => assertServerlessArticle(fixture + '\n' + unsafe), assert.AssertionError, unsafe + ' rejected');
});

test('STY-11 source fixture locks the eleven identities and citation roles', () => {
  const remote = Object.entries(REMOTE_SOURCES).map(([id, expected]) => ({id, ...expected, expected_final_transport_locator: expected.transport_locator, license_family_id: id + '-family', allowed_evidence_roles: expected.roles}));
  const original = {id: SOURCE_IDS.at(-1), ...ORIGINAL_SOURCE, expected_final_transport_locator: ORIGINAL_SOURCE.transport_locator, license_family_id: 'original-family', allowed_evidence_roles: ORIGINAL_SOURCE.roles};
  const ledger = {sources: [...remote, original], documents: {[ARTICLE]: {citations: [...remote.map(({id, roles}, index) => ({source_id: id, roles, manifest_primary: index === 0, usage_mode: 'facts-summary'})), {source_id: original.id, roles: ORIGINAL_SOURCE.roles, manifest_primary: false, usage_mode: 'original-illustration'}]}}};
  assertServerlessSources(ledger);
  for (const id of SOURCE_IDS) { const changed = structuredClone(ledger); changed.sources = changed.sources.filter((source) => source.id !== id); assert.throws(() => assertServerlessSources(changed), assert.AssertionError, id + ' source deletion rejected'); }
  const changed = structuredClone(ledger); changed.documents[ARTICLE].citations[0].manifest_primary = false; changed.documents[ARTICLE].citations[1].manifest_primary = true; assert.throws(() => assertServerlessSources(changed), assert.AssertionError, 'primary mutation rejected');
  const copied = structuredClone(ledger); copied.documents[ARTICLE].citations[0].usage_mode = 'copied-text'; assert.throws(() => assertServerlessSources(copied), assert.AssertionError, 'non-conservative citation rejected');
  const boundary = structuredClone(ledger); boundary.sources[0].usage_boundary = 'unrestricted copied diagrams and guarantees'; assert.throws(() => assertServerlessSources(boundary), assert.AssertionError, 'usage-boundary mutation rejected');
  for (const field of ['canonical_locator', 'transport_locator', 'expected_final_transport_locator', 'version', 'license', 'copyright_policy']) { const drift = structuredClone(ledger); drift.sources[0][field] = 'drifted'; assert.throws(() => assertServerlessSources(drift), assert.AssertionError, field + ' source-rights drift rejected'); }
  const roles = structuredClone(ledger); roles.sources[0].allowed_evidence_roles = ['comparison']; roles.documents[ARTICLE].citations[0].roles = ['comparison']; assert.throws(() => assertServerlessSources(roles), assert.AssertionError, 'source and citation role drift rejected');
});

test('STY-11 diagram helpers reject terminal, style, collision, and paint mutations', () => {
  const source = '<svg><style>#host > .edge[data-edge-id="x"] { stroke:#0F766E !important; font-size:45px; }</style><g id="host"><path class="edge" data-edge-id="x" style="stroke:#000" d="M 0 0 L 30 0"/></g></svg>';
  const svg = parseSvg(source); const edge = svg.edges.find(({attributes}) => attributes.get('data-edge-id') === 'x');
  assert.equal(svgPresentationValue(source, edge, 'stroke'), '#0F766E', 'effective cascade style');
  assert.deepEqual(parsePathPoints(edge.attributes.get('d')), [{x: 0, y: 0}, {x: 30, y: 0}], 'real SVG path points');
  const left = {attributes: new Map([['id', 'node-left']]), geometry: new Map([['x', '0'], ['y', '0'], ['width', '100'], ['height', '100']])};
  const right = {attributes: new Map([['id', 'node-right']]), geometry: new Map([['x', '300'], ['y', '0'], ['width', '100'], ['height', '100']])};
  const raw = '<mxCell id="edge" edge="1" source="node-left" target="node-right" style="exitX=1;exitY=0.5;exitDx=0;exitDy=0;exitPerimeter=1;entryX=0;entryY=0.5;entryDx=0;entryDy=0;entryPerimeter=1;"><mxGeometry relative="1" as="geometry"><Array as="points"><mxPoint x="200" y="50"/></Array></mxGeometry></mxCell>';
  assert.deepEqual(drawioRoute(parseDrawio(raw).edges[0], new Map([['node-left', left], ['node-right', right]])), [{x: 100, y: 50}, {x: 200, y: 50}, {x: 300, y: 50}], 'real terminals and waypoint');
  assert.throws(() => drawioRoute(parseDrawio(raw.replace('exitX=1', 'exitX=0.7')).edges[0], new Map([['node-left', left], ['node-right', right]])), assert.AssertionError, 'non-perimeter terminal rejected');
  const clear = {left: 40, right: 60, top: 24, bottom: 28}; assertRouteGlyphClearance([{x: 0, y: 0}, {x: 100, y: 0}], clear, 'fixture glyph');
  assert.throws(() => assertRouteGlyphClearance([{x: 0, y: 0}, {x: 100, y: 0}], {...clear, top: -2, bottom: 2}, 'overlap'), assert.AssertionError, 'glyph collision rejected');
  assert.equal(partialCollinearOverlap({x: 0, y: 0}, {x: 20, y: 0}, {x: 10, y: 0}, {x: 30, y: 0}), true, 'partial collinear overlap measured');
  assert.throws(() => assertNoLaterPaintMask([{x: 0, y: 0}, {x: 30, y: 0}], [{left: 10, right: 20, top: -1, bottom: 1, alpha: 1}]), assert.AssertionError, 'later paint mask rejected');
  assert.deepEqual(alphaCompose({red: 0, green: 0, blue: 0, alpha: 0}, {red: 255, green: 255, blue: 255, alpha: .5}), {red: 255, green: 255, blue: 255, alpha: .5}, 'source-over alpha');
});

test('STY-11 implementation remains RED until its article, sources, relations, diagram, and projection exist', async () => {
  const source = file(ARTICLE); assert.ok(source, ARTICLE + ' must exist after implementation');
  assertServerlessArticle(source);
  const ledger = JSON.parse(readFileSync('data/source-ledger.json', 'utf8')); assertServerlessSources(ledger);
  const diagram = file(DRAWIO); const svg = file(SVG); assert.ok(diagram && svg, 'STY-11 diagram pair');
  assertServerlessDiagram(diagram, svg);
  await assertServerlessRelationsAndStageA();
});
