import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import test from 'node:test';
import {fileURLToPath} from 'node:url';

import {analyzeCaseText} from '../.codex/skills/writing-architecture-cases/scripts/analyze_case_density.mjs';
import {findMarkdownHeadings, parseFrontMatter, readContentDocuments} from '../scripts/content-metadata.mjs';
import {extractInternalLinks} from '../scripts/content-relations.mjs';
import {extractExternalLinks} from '../scripts/source-ledger.mjs';
import {parseMdxVisibleCopy} from '../scripts/visible-copy.mjs';
import {knowledgeTypeContracts} from '../scripts/content-schema.mjs';
import {handleHorizontalArrowKey} from '../src/components/KeyboardScrollableRegion/handleHorizontalArrowKey.mjs';

const ARTICLE = 'content/methods/mth-07-fde-enterprise-ai-delivery.mdx';
const DRAWIO = 'diagrams/mth-07-fde-enterprise-ai-delivery-gates.drawio';
const SVG = 'static/img/diagrams/mth-07-fde-enterprise-ai-delivery-gates.svg';
const H2 = ['学习问题','一页摘要','事实边界','交付门禁图','四阶段控制流','证据、产物与责任','架构决策与权衡','生产化分析','可迁移经验','来源'];
const TRANSFER_H3 = ['可直接复用的机制','只能有限类比的部分','不应照搬的部分'];
const STAGES = ['进场期','立项期','交付期','放大期'];
const GATES = ['需求考古','流程测绘','切口选择','验收标准工程','POC 纪律','职责契约','知识结构化','人机分工设计','合规与风险兜底','渐进放量','信任运营','资产化复制'];
const STAGE_IDS = ['stage-entry','stage-initiation','stage-delivery','stage-scale'];
const GATE_IDS = GATES.map((_, index) => `gate-${String(index + 1).padStart(2, '0')}`);
const FEEDBACK_IDS = ['feedback-rollout-to-acceptance','feedback-compliance-to-scope','feedback-reuse-to-contract'];
const FEEDBACK_TOPOLOGY = new Map([
  ['feedback-rollout-to-acceptance', ['gate-10', 'gate-04']],
  ['feedback-compliance-to-scope', ['gate-09', 'gate-03']],
  ['feedback-reuse-to-contract', ['gate-12', 'gate-06']],
]);
const RESPONSIBILITY_IDS = ['owner-customer','owner-delivery','owner-product','owner-platform','owner-security-data'];
const TOPIC_ID = 'MTH-07';
const ROUTE = '/methods/mth-07';
const SOURCE_IDS = ['src-wechat-fde-12-core-capabilities', 'src-nist-ai-rmf-1-0', 'src-google-sre-canarying-releases', 'src-atlas-mth07-fde-delivery-gates'];
const REMOTE_SOURCES = new Map([
  ['src-wechat-fde-12-core-capabilities', {canonical_locator: 'https://mp.weixin.qq.com/s/6_-S0yIVlCtqW8U8JfwdGA', title: '一文读懂：FDE的12项核心能力', author_or_org: '李伟山（腾讯云开发者）', published_at: '2026-08-13', allowed: ['historical-context']}],
  ['src-nist-ai-rmf-1-0', {canonical_locator: 'https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-ai-rmf-10', title: 'Artificial Intelligence Risk Management Framework (AI RMF 1.0)', author_or_org: 'National Institute of Standards and Technology', version: 'NIST AI 100-1', published_at: '2023-01-26'}],
  ['src-google-sre-canarying-releases', {canonical_locator: 'https://sre.google/workbook/canarying-releases/', title: 'Canarying Releases', author_or_org: 'Google SRE'}],
]);
const RELATIONS = {depends_on: ['MTH-01', 'MTH-04', 'MTH-06'], adjacent_topics: ['MTH-01', 'MTH-04', 'MTH-06'], related_cases: ['/cases/temporal-saga-durable-execution'], related_questions: []};
const EXACT_METADATA = {
  title: '企业 AI 前线部署：从 POC 到可复制系统的交付门禁', slug: ROUTE, content_type: 'method', status: 'reviewed', difficulty: 'advanced', analyzed_at: '2026-08-13', source_cutoff: '2026-08-13', review_policy: 'quarterly-version-sensitive', confidence: 'high', domains: ['software-architecture', 'ai-systems'], agent_patterns: ['human-in-the-loop'], protocols: [], quality_attributes: ['reliability', 'security', 'maintainability'], tags: ['企业 AI', 'FDE', '交付门禁', 'POC'], summary: '用四阶段十二门禁把企业 AI 的现场问题、验收证据、生产责任、渐进放量与复制边界连接成可停止的交付闭环。', topic_id: TOPIC_ID, priority: 'P1', ...RELATIONS,
};
const TABLE_COLUMNS = ['阶段', '门禁', '风险', '机制', '证据', '通过条件', '责任人', '失败/返回目标'];
const GATE_ROWS = [
  ['进场期','需求考古','把意向当需求','访谈、工单、流程记录交叉核验','问题与基线记录','问题、角色、基线和来源可追溯','客户业务负责人','停止或返回需求考古'],
  ['进场期','流程测绘','局部自动化破坏全流程','测绘等待点、例外、决定和系统边界','现状流程图','明确失败回路与不可自动化步骤','交付/FDE 负责人','返回需求考古'],
  ['进场期','切口选择','高价值切口不可控','按价值、可测量性、可逆性与合规风险评分','切口评分','可测、可逆且数据治理条件满足','产品工程负责人','返回流程测绘'],
  ['立项期','验收标准工程','演示替代验收','建立评估集、阈值、预算和失败分级','可执行验收包','可复现并关联阶段退出条件','客户业务负责人','返回切口选择'],
  ['立项期','POC 纪律','POC 无限外推','限定假设、样本、时间盒和退出标准','POC 假设卡','只验证声明范围内假设','交付/FDE 负责人','停止或返回验收标准工程'],
  ['立项期','职责契约','共同负责导致无人负责','写明输入、决定、审批、值守和终止权','责任契约','每项风险有单一可停止的责任人','客户业务负责人','返回验收标准工程'],
  ['交付期','知识结构化','知识不可追溯或无授权','固定来源、版本、冲突和撤回路径','知识来源清单','每项知识可追溯且有授权边界','产品工程负责人','返回职责契约'],
  ['交付期','人机分工设计','模型输出越权执行','分离程序控制、AI 候选和人工授权','人机职责矩阵','不可逆动作有人授权与审计','客户业务负责人','返回职责契约'],
  ['交付期','合规与风险兜底','风险在上线后暴露','审查数据、场景、降级、停机和复核','风险与合规决定','停止权、降级和回退可触发','安全与数据负责人','返回切口选择'],
  ['放大期','渐进放量','一次性扩大影响半径','影子、白名单、对照、回滚和容量预算','放量阈值记录 v1.0','质量、失败率、成本和队列阈值均通过 v1.0','平台与运维负责人','返回验收标准工程'],
  ['放大期','信任运营','一次演示替代运行信任','监测质量、申诉、漂移、成本和人工负担','生产观测记录 v1.0','质量、成本、人工负担阈值均通过 v1.0','客户业务负责人','返回人机分工设计'],
  ['放大期','资产化复制','把客户特定逻辑当通用资产','分离通用核心、客户资产、许可证与运行责任','复制成本上限记录 v1.0','差异成本上限、数据边界和许可均通过 v1.0','交付/FDE 负责人','返回职责契约'],
];
const REQUIRED_WRAPPERS = [
  {aria: '企业 AI 四阶段十二门禁图，可横向滚动', className: 'architecture-diagram-scroll'},
  {aria: '企业 AI 十二门禁执行表，可横向滚动', className: 'table-wrapper table-wrapper--mapping diagram-wrapper--scroll-owner'},
  {aria: '人、AI 与程序职责及停止条件表，可横向滚动', className: 'table-wrapper table-wrapper--mapping diagram-wrapper--scroll-owner'},
];

const contentRoot = fileURLToPath(new URL('../content/', import.meta.url));
const [documents, ledger, manifest, projectStatus] = await Promise.all([readContentDocuments(contentRoot), readFile(new URL('../data/source-ledger.json', import.meta.url), 'utf8').then(JSON.parse), readFile(new URL('../src/generated/topic-manifest.json', import.meta.url), 'utf8').then(JSON.parse), readFile(new URL('../src/generated/project-status.json', import.meta.url), 'utf8').then(JSON.parse)]);
const article = documents.find(({file}) => `content/${file}` === ARTICLE);

function visible(source) { return parseMdxVisibleCopy(source, ARTICLE, {includeStructure: true}).blocks.map(({text}) => text).join('\n'); }
function requiredArticle() { assert.ok(article, `${ARTICLE} must exist after implementation`); return article; }
function headings(source, level) { return findMarkdownHeadings(source).filter((item) => item.level === level).map(({text}) => text); }
function section(source, heading, next) { const list = findMarkdownHeadings(source).filter(({level}) => level === 2); const index = list.findIndex(({text}) => text === heading); assert.ok(index >= 0, heading); const end = next ? list.findIndex(({text}, i) => i > index && text === next) : -1; assert.ok(!next || end >= 0, next); return source.slice(source.indexOf('\n', list[index].offset) + 1, end >= 0 ? list[end].offset : source.length); }
function table(source) { const raw = [...source.matchAll(/(?:^|\n)(\|[^\n]+\|\n\|(?:\s*:?-{3,}:?\s*\|)+\n(?:\|[^\n]+\|\n?)+)/gu)].map(([, value]) => value.trim()).find((value) => value.startsWith(`| ${TABLE_COLUMNS.join(' | ')} |`)); assert.ok(raw, 'twelve gate execution table'); return raw.split('\n').slice(2).map((line) => line.slice(1, -1).split('|').map((cell) => cell.trim())); }
function assertMetadataAndHeadings(source) { assert.deepEqual(parseFrontMatter(source), EXACT_METADATA, 'exact canonical metadata'); assert.deepEqual(headings(source, 2), H2, 'MTH-07 only ten H2s'); assert.deepEqual(headings(section(source, '可迁移经验', '来源'), 3), TRANSFER_H3, 'transfer H3s scoped to 可迁移经验'); }
function assertGateRows(source) { const rows = table(source); assert.deepEqual(rows, GATE_ROWS, 'auditable, exact ordered gate contracts'); for (const [index, row] of rows.entries()) { assert.equal(row.length, 8, `${GATES[index]} eight fields`); assert.equal(row[0], STAGES[Math.floor(index / 3)]); assert.equal(row[1], GATES[index]); for (let field = 2; field < 8; field += 1) assert.ok(row[field].length >= 2, `${GATES[index]} field ${field}`); } }
function assertEvidenceAndResponsibilities(source) {
  const text = visible(source); for (const label of ['来源事实', '独立证据', 'Tego Arch 推断']) assert.match(text, new RegExp(label, 'u'), `${label} label`);
  for (const sentence of text.split(/[。！？!?\n]+/u)) assert.equal(/(?:市场|薪资|政策).{0,32}\d/u.test(sentence), false, 'current four-source set cannot support numeric market/salary/policy claims');
  assert.match(text, /NIST AI RMF 1\.0 支持评估、监测与人工覆盖机制/u, 'accepted nonnumeric independent claim');
  const clauses = ['POC 成功不等于生产可用','生产可用不等于验收通过','验收通过不等于放量','放量不等于复制','程序负责权限校验、确定性规则、审计记录和回滚开关','AI 只负责检索、分类、生成候选或建议，不得最终授权不可逆动作','人负责授权不可逆动作、决定放量与终止','人工队列有上限、时限和能力约束','客户业务负责人拥有明确停止权'];
  for (const clause of clauses) assert.ok(text.includes(clause), clause);
  for (const forbidden of [/POC.{0,12}(?:就是|(?<!不)等于).{0,12}生产/u, /生产.{0,12}(?:就是|(?<!不)等于).{0,12}验收/u, /验收.{0,12}(?:就是|(?<!不)等于).{0,12}放量/u, /放量.{0,12}(?:就是|(?<!不)等于).{0,12}复制/u]) assert.doesNotMatch(text, forbidden, `conflation ${forbidden}`);
}
function assertWrappersAndArrowBehavior(source) {
  assert.match(source, /import \{handleHorizontalArrowKey\} from '@site\/src\/components\/KeyboardScrollableRegion\/handleHorizontalArrowKey\.mjs';/u, 'uses canonical handler import'); const region = {scrollLeft: 0, scrollWidth: 200, clientWidth: 100}; let prevented = false; handleHorizontalArrowKey({key: 'ArrowRight', target: region, currentTarget: region, altKey: false, ctrlKey: false, metaKey: false, shiftKey: false, preventDefault: () => { prevented = true; }}); assert.equal(region.scrollLeft, 40, 'canonical ArrowRight scrolls focused overflow region'); assert.equal(prevented, true, 'canonical handler prevents default');
  for (const {aria, className} of REQUIRED_WRAPPERS) assert.equal(source.split(`<div className="${className}" role="region" aria-label="${aria}" tabIndex={0} onKeyDown={handleHorizontalArrowKey}>`).length - 1, 1, aria);
}
function attrs(raw) { return new Map([...raw.matchAll(/([\w:-]+)="([^"]*)"/gu)].map(([, key, value]) => [key, value])); }
function drawioCells(source) { return [...source.matchAll(/<mxCell\b([^>]*)>([\s\S]*?)<\/mxCell>|<mxCell\b([^>]*)\/>/gu)].map((match) => ({attrs: attrs(match[1] ?? match[3] ?? ''), geometry: attrs((match[2] ?? '').match(/<mxGeometry\b([^>]*)/u)?.[1] ?? ''), body: match[2] ?? ''})); }
function svgElements(source, name) { return [...source.matchAll(new RegExp(`<${name}\\b([^>]*)>`, 'gu'))].map((match) => ({attrs: attrs(match[1]), index: match.index, raw: match[0]})); }
function svgNodes(source) { return [...source.matchAll(/<g\b([^>]*)data-node-id="([^"]+)"([^>]*)>([\s\S]*?)<\/g>/gu)].map(([, before, id, after, body], index) => ({id, attrs: attrs(`${before}${after}`), body, index})); }
function svgEdges(source) { return svgElements(source, 'path').filter(({attrs: item}) => item.has('data-edge-id')).map(({attrs: item, index}) => ({id: item.get('data-edge-id'), attrs: item, index})); }
function rectFromNode(node) { const rect = node.body.match(/<rect\b([^>]*)\/>/u); assert.ok(rect, `${node.id} rendered rect`); const item = attrs(rect[1]); return Object.fromEntries(['x', 'y', 'width', 'height'].map((key) => [key, Number(item.get(key))])); }
function boxContains(outer, inner) { return inner.x >= outer.x && inner.y >= outer.y && inner.x + inner.width <= outer.x + outer.width && inner.y + inner.height <= outer.y + outer.height; }
function points(d) { return [...d.matchAll(/[ML]\s*([\d.]+)[ ,]([\d.]+)/gu)].map(([, x, y]) => ({x: Number(x), y: Number(y)})); }
function pointToSegment(point, start, end) { const dx = end.x - start.x; const dy = end.y - start.y; const t = Math.max(0, Math.min(1, ((point.x - start.x) * dx + (point.y - start.y) * dy) / (dx * dx + dy * dy))); return Math.hypot(point.x - (start.x + t * dx), point.y - (start.y + t * dy)); }
function polygonPoints(raw) { return [...raw.matchAll(/([\d.]+)[ ,]([\d.]+)/gu)].map(([, x, y]) => ({x: Number(x), y: Number(y)})); }
function boxesOverlap(left, right) { return left.x < right.x + right.width && left.x + left.width > right.x && left.y < right.y + right.height && left.y + left.height > right.y; }
function elementBox(element) { const a = element.attrs; if (element.raw.startsWith('<rect')) return {x: Number(a.get('x')), y: Number(a.get('y')), width: Number(a.get('width')), height: Number(a.get('height'))}; if (element.raw.startsWith('<polygon')) { const items = polygonPoints(a.get('points') ?? ''); return {x: Math.min(...items.map(({x}) => x)), y: Math.min(...items.map(({y}) => y)), width: Math.max(...items.map(({x}) => x)) - Math.min(...items.map(({x}) => x)), height: Math.max(...items.map(({y}) => y)) - Math.min(...items.map(({y}) => y))}; } return null; }
function cssRule(source, selector, property) { const rule = source.match(new RegExp(`${selector.replace('.', '\\.') }\\s*\\{([^}]*)\\}`, 'u')); assert.ok(rule, `${selector} rule`); const value = rule[1].match(new RegExp(`${property}:\\s*([^;]+)`, 'u'))?.[1]?.trim(); assert.ok(value, `${selector} ${property}`); return value; }
function rgb(hex) { const value = hex.replace('#', ''); return [0, 2, 4].map((index) => Number.parseInt(value.slice(index, index + 2), 16) / 255).map((item) => item <= .03928 ? item / 12.92 : ((item + .055) / 1.055) ** 2.4); }
function contrast(foreground, background) { const luminance = (color) => { const [r, g, b] = rgb(color); return .2126 * r + .7152 * g + .0722 * b; }; const [a, b] = [luminance(foreground), luminance(background)].sort((left, right) => right - left); return (a + .05) / (b + .05); }
function segmentOverlap(a, b, c, d) { const cross = (p, q, r) => (q.x - p.x) * (r.y - p.y) - (q.y - p.y) * (r.x - p.x); if (Math.abs(cross(a, b, c)) > .01 || Math.abs(cross(a, b, d)) > .01) return false; const axis = Math.abs(a.x - b.x) > Math.abs(a.y - b.y) ? 'x' : 'y'; return Math.max(Math.min(a[axis], b[axis]), Math.min(c[axis], d[axis])) < Math.min(Math.max(a[axis], b[axis]), Math.max(c[axis], d[axis])) - .01; }
function assertDiagram(drawio, svg) {
  const cells = drawioCells(drawio); assert.match(drawio, /<mxfile\b/u); assert.match(svg, /<svg\b[^>]*role="img"/u);
  const vertices = new Map(cells.filter(({attrs: item}) => item.get('vertex') === '1').map((cell) => [cell.attrs.get('id'), cell])); const drawEdges = new Map(cells.filter(({attrs: item}) => item.get('edge') === '1').map((cell) => [cell.attrs.get('id'), cell])); const nodes = new Map(svgNodes(svg).map((node) => [node.id, node])); const edges = new Map(svgEdges(svg).map((edge) => [edge.id, edge]));
  const labelById = new Map([...STAGE_IDS, ...GATE_IDS, ...RESPONSIBILITY_IDS, 'stop-authority'].map((id, index) => [id, [...STAGES, ...GATES, '客户业务', '交付/FDE', '产品工程', '平台与运维', '安全与数据', '停止/回退'][index]]));
  for (const id of [...STAGE_IDS, ...GATE_IDS, ...RESPONSIBILITY_IDS, 'stop-authority']) { assert.ok(vertices.has(id), `Draw.io ${id}`); assert.ok(nodes.has(id), `SVG ${id}`); const dg = vertices.get(id).geometry; assert.deepEqual(rectFromNode(nodes.get(id)), Object.fromEntries(['x','y','width','height'].map((key) => [key, Number(dg.get(key))])), `${id} Draw.io/SVG bounds parity`); assert.ok(nodes.get(id).body.includes(`>${labelById.get(id)}<`), `${id} human-readable semantic label`); assert.doesNotMatch(nodes.get(id).body, new RegExp(`>${id}<`, 'u'), `${id} does not expose machine ID as label`); }
  for (let index = 0; index < GATE_IDS.length; index += 1) assert.ok(boxContains(rectFromNode(nodes.get(STAGE_IDS[Math.floor(index / 3)])), rectFromNode(nodes.get(GATE_IDS[index]))), `${GATE_IDS[index]} contained in its stage`);
  for (const [id, [expectedSource, expectedTarget]] of FEEDBACK_TOPOLOGY) { const edge = drawEdges.get(id); assert.ok(edge, `Draw.io feedback ${id}`); assert.ok(edges.has(id), `SVG feedback ${id}`); assert.equal(edge.attrs.get('source'), expectedSource, `${id} exact source`); assert.equal(edge.attrs.get('target'), expectedTarget, `${id} exact target`); assert.match(edge.attrs.get('style') ?? '', /perimeter=1/u, `${id} perimeter port`); for (const portName of ['exitX', 'exitY', 'entryX', 'entryY']) assert.match(edge.attrs.get('style') ?? '', new RegExp(`${portName}=[\\d.]+`, 'u'), `${id} ${portName} terminal`); const waypointTags = [...edge.body.matchAll(/<mxPoint\b([^>]*)/gu)].map(([, raw]) => attrs(raw)); assert.ok(waypointTags.length > 0 && /<Array\b[^>]*as="points"/u.test(edge.body), `${id} waypoint array`); const path = points(edges.get(id).attrs.get('d')); assert.equal(path.length, waypointTags.length + 2, `${id} complete Draw.io/SVG polyline count`); const sourceRect = rectFromNode(nodes.get(expectedSource)); const targetRect = rectFromNode(nodes.get(expectedTarget)); const port = (name) => Number((edge.attrs.get('style').match(new RegExp(`${name}=([\\d.]+)`, 'u')) ?? [])[1]); const drawPolyline = [{x: sourceRect.x + sourceRect.width * port('exitX'), y: sourceRect.y + sourceRect.height * port('exitY')}, ...waypointTags.map((item) => ({x: Number(item.get('x')), y: Number(item.get('y'))})), {x: targetRect.x + targetRect.width * port('entryX'), y: targetRect.y + targetRect.height * port('entryY')}]; assert.deepEqual(path, drawPolyline, `${id} full Draw.io/SVG route parity`); assert.equal(edges.get(id).attrs.get('data-source'), expectedSource); assert.equal(edges.get(id).attrs.get('data-target'), expectedTarget); }
  assert.equal(new Set(FEEDBACK_IDS).size, 3); assert.ok(nodes.has('stop-authority')); assert.equal(RESPONSIBILITY_IDS.every((id) => nodes.has(id)), true, 'responsibility band');
  const canvas = svgElements(svg, 'rect').find(({attrs: item}) => item.get('data-canvas') === 'true'); assert.ok(canvas, 'actual canvas'); assert.equal(Number(canvas.attrs.get('opacity') ?? 1), 1, 'canvas is actually opaque'); const background = canvas.attrs.get('fill'); const edgeStroke = cssRule(svg, '.edge', 'stroke'); const labelFill = cssRule(svg, '.edge-label', 'fill'); assert.ok(contrast(edgeStroke, background) >= 4.5, 'effective edge contrast'); assert.ok(contrast(labelFill, background) >= 4.5, 'effective label contrast'); const marker = svg.match(/<marker\b([^>]*)>([\s\S]*?)<\/marker>/u); assert.ok(marker); const markerAttrs = attrs(marker[1]); assert.ok(Number(markerAttrs.get('markerWidth')) >= 16 && Number(markerAttrs.get('markerHeight')) >= 16, 'actual marker dimensions'); assert.match(marker[2], /<(?:path|polygon|polyline)\b[^>]*(?:fill|stroke)=/u, 'marker has visible geometry'); for (const edge of edges.values()) { assert.match(edge.attrs.get('marker-end') ?? '', /^url\(#[-\w]+\)$/u, `${edge.id} resolved marker-end`); assert.equal(edge.attrs.get('data-stroke') ?? edgeStroke, edgeStroke, `${edge.id} stroke parity`); assert.equal(edge.attrs.get('data-dash') ?? 'none', 'none', `${edge.id} dash parity`); }
  const scale = 800 / Number((svg.match(/viewBox="0 0 ([\d.]+) [\d.]+"/u) ?? [])[1]); assert.ok(Number.isFinite(scale), 'actual viewBox scale'); const semanticLabels = svgElements(svg, 'text'); for (const label of semanticLabels) assert.ok(Number(label.attrs.get('font-size')) * scale >= 15, 'essential text >=15 CSS px at 800px'); const labels = semanticLabels.filter(({attrs: item}) => item.has('data-edge-label')); assert.equal(labels.length, FEEDBACK_IDS.length, 'one edge label per feedback route'); for (const label of labels) { const edge = edges.get(label.attrs.get('data-edge-label')); assert.ok(edge); const text = String(svg.slice(label.index).match(/^<text[^>]*>([^<]+)<\/text>/u)?.[1] ?? ''); const font = Number(label.attrs.get('font-size')); const box = {x: Number(label.attrs.get('x')), y: Number(label.attrs.get('y')) - font, width: Array.from(text).length * font * .6, height: font}; assert.ok(box.width > 0, 'derived text bounding box'); const path = points(edge.attrs.get('d')); const probes = [{x: box.x, y: box.y}, {x: box.x + box.width, y: box.y}, {x: box.x, y: box.y + box.height}, {x: box.x + box.width, y: box.y + box.height}]; let clearance = Infinity; for (const probe of probes) for (let index = 1; index < path.length; index += 1) clearance = Math.min(clearance, pointToSegment(probe, path[index - 1], path[index])); assert.ok(clearance * scale >= 8, 'derived full label box to stroke clearance'); }
  const allSegments = [...edges.values()].flatMap((edge) => points(edge.attrs.get('d')).slice(1).map((end, index) => ({id: edge.id, start: points(edge.attrs.get('d'))[index], end}))); for (let left = 0; left < allSegments.length; left += 1) for (let right = left + 1; right < allSegments.length; right += 1) if (allSegments[left].id !== allSegments[right].id) assert.equal(segmentOverlap(allSegments[left].start, allSegments[left].end, allSegments[right].start, allSegments[right].end), false, 'no partial shared segment');
  const pathBoxes = [...edges.values()].map((edge) => { const route = points(edge.attrs.get('d')); return {x: Math.min(...route.map(({x}) => x)), y: Math.min(...route.map(({y}) => y)), width: Math.max(...route.map(({x}) => x)) - Math.min(...route.map(({x}) => x)), height: Math.max(...route.map(({y}) => y)) - Math.min(...route.map(({y}) => y))}; }); for (const element of [...svgElements(svg, 'rect'), ...svgElements(svg, 'polygon')].filter(({index, attrs: item}) => index > Math.max(...svgEdges(svg).map(({index}) => index)) && item.get('fill') !== 'none' && Number(item.get('opacity') ?? 1) > 0)) { const box = elementBox(element); if (box && pathBoxes.some((pathBox) => boxesOverlap(box, pathBox))) assert.fail(`later painted shape ${element.index} overlaps connector`); }
}
function mutate(source, from, to, label) { const result = source.replace(from, to); assert.notEqual(result, source, `${label} mutation is non-no-op`); return result; }
function fixtureArticle() { const headingText = H2.map((heading) => heading === '可迁移经验' ? `## ${heading}\n${TRANSFER_H3.map((item) => `### ${item}`).join('\n')}` : `## ${heading}`).join('\n\n'); const metadata = Object.entries(EXACT_METADATA).map(([key, value]) => Array.isArray(value) ? `${key}:\n${value.map((item) => `  - ${item}`).join('\n')}` : `${key}: ${value}`).join('\n'); return `---\n${metadata}\n---\n\nimport {handleHorizontalArrowKey} from '@site/src/components/KeyboardScrollableRegion/handleHorizontalArrowKey.mjs';\n\n${headingText}\n\n| ${TABLE_COLUMNS.join(' | ')} |\n| ${TABLE_COLUMNS.map(() => '---').join(' | ')} |\n${GATE_ROWS.map((row) => `| ${row.join(' | ')} |`).join('\n')}\n\n来源事实。独立证据。Tego Arch 推断。NIST AI RMF 1.0 支持评估、监测与人工覆盖机制。POC 成功不等于生产可用。生产可用不等于验收通过。验收通过不等于放量。放量不等于复制。程序负责权限校验、确定性规则、审计记录和回滚开关。AI 只负责检索、分类、生成候选或建议，不得最终授权不可逆动作。人负责授权不可逆动作、决定放量与终止。人工队列有上限、时限和能力约束。客户业务负责人拥有明确停止权。\n\n${REQUIRED_WRAPPERS.map(({aria, className}) => `<div className="${className}" role="region" aria-label="${aria}" tabIndex={0} onKeyDown={handleHorizontalArrowKey}></div>`).join('\n')}`; }
function fixtureDiagram() { const boxes = new Map(); STAGE_IDS.forEach((id, index) => boxes.set(id, {x: 20 + index * 190, y: 20, width: 180, height: 250})); GATE_IDS.forEach((id, index) => boxes.set(id, {x: 35 + Math.floor(index / 3) * 190, y: 50 + (index % 3) * 65, width: 150, height: 45})); RESPONSIBILITY_IDS.forEach((id, index) => boxes.set(id, {x: 20 + index * 145, y: 310, width: 130, height: 40})); boxes.set('stop-authority', {x: 720, y: 180, width: 100, height: 45}); const captions = new Map([...STAGE_IDS.map((id, index) => [id, STAGES[index]]), ...GATE_IDS.map((id, index) => [id, GATES[index]]), ['owner-customer', '客户业务'], ['owner-delivery', '交付/FDE'], ['owner-product', '产品工程'], ['owner-platform', '平台与运维'], ['owner-security-data', '安全与数据'], ['stop-authority', '停止/回退']]); const vertex = (id) => { const box = boxes.get(id); return `<mxCell id="${id}" vertex="1"><mxGeometry x="${box.x}" y="${box.y}" width="${box.width}" height="${box.height}" as="geometry"/></mxCell>`; }; const feedback = FEEDBACK_IDS.map((id, index) => { const [source, target] = FEEDBACK_TOPOLOGY.get(id); return `<mxCell id="${id}" edge="1" source="${source}" target="${target}" style="perimeter=1;exitX=1;exitY=0.5;entryX=0;entryY=0.5;endArrow=block;"><mxGeometry relative="1" as="geometry"><Array as="points"><mxPoint x="${600 + index * 10}" y="${110 + index * 20}"/></Array></mxGeometry></mxCell>`; }).join(''); const drawio = `<mxfile><diagram><mxGraphModel><root>${[...boxes.keys()].map(vertex).join('')}${feedback}</root></mxGraphModel></diagram></mxfile>`; const groups = [...boxes.keys()].map((id) => { const box = boxes.get(id); return `<g data-node-id="${id}"><rect x="${box.x}" y="${box.y}" width="${box.width}" height="${box.height}" fill="#ffffff"/><text x="${box.x + 8}" y="${box.y + 20}" font-size="16">${captions.get(id)}</text></g>`; }).join(''); const paths = FEEDBACK_IDS.map((id, index) => { const [source, target] = FEEDBACK_TOPOLOGY.get(id); const start = boxes.get(source); const end = boxes.get(target); const sx = start.x + start.width; const sy = start.y + start.height / 2; const tx = end.x; const ty = end.y + end.height / 2; const midX = 600 + index * 10; const midY = 110 + index * 20; return `<path class="edge" data-edge-id="${id}" data-source="${source}" data-target="${target}" data-stroke="#1d4ed8" data-dash="none" d="M ${sx} ${sy} L ${midX} ${midY} L ${tx} ${ty}" marker-end="url(#arrow)"/><text class="edge-label" data-edge-label="${id}" x="${midX}" y="${midY - 18}" font-size="16">反馈</text>`; }).join(''); const svg = `<svg role="img" viewBox="0 0 840 380"><style>.edge { stroke: #1d4ed8; fill: none; stroke-width: 2; } .edge-label { fill: #111827; }</style><defs><marker id="arrow" markerWidth="18" markerHeight="18"><path d="M 0 0 L 16 8 L 0 16 z" fill="#1d4ed8"/></marker></defs><rect data-canvas="true" x="0" y="0" width="840" height="380" fill="#ffffff"/>${groups}${paths}</svg>`; return {drawio, svg}; }

test('MTH-07 helper contracts are green after non-no-op RED mutation fixtures', () => {
  const source = fixtureArticle(); assertMetadataAndHeadings(source); assertGateRows(source); assertEvidenceAndResponsibilities(source); assertWrappersAndArrowBehavior(source);
  const extraH3 = mutate(source, '### 不应照搬的部分', '### 关键源码导读\n\n### 不应照搬的部分', 'extra transfer H3'); const metadataMutations = [mutate(source, 'topic_id: MTH-07', 'topic_id: MTH-99', 'wrong topic'), mutate(source, 'content_type: method', 'content_type: style', 'wrong type'), mutate(source, '## 一页摘要', '## 完整演练', 'fallback headings'), mutate(source, '### 不应照搬的部分', '', 'missing transfer H3'), extraH3]; metadataMutations.forEach((item) => assert.throws(() => assertMetadataAndHeadings(item), assert.AssertionError));
  for (const row of GATE_ROWS) { for (let index = 0; index < row.length; index += 1) { const changed = [...row]; changed[index] = '错误字段'; const mutation = mutate(source, `| ${row.join(' | ')} |`, `| ${changed.join(' | ')} |`, `${row[1]} field`); assert.throws(() => assertGateRows(mutation), assert.AssertionError); } const deletion = mutate(source, `| ${row.join(' | ')} |\n`, '', `${row[1]} deletion`); assert.throws(() => assertGateRows(deletion), assert.AssertionError); }
  const ownerlessDuplicate = mutate(source, `| ${GATE_ROWS.at(-1).join(' | ')} |`, `| ${GATE_ROWS.at(-1).slice(0, 6).join(' | ')} |  | ${GATE_ROWS.at(-1)[7]} |\n| ${GATE_ROWS.at(-1).join(' | ')} |`, 'ownerless duplicate'); assert.throws(() => assertGateRows(ownerlessDuplicate), assert.AssertionError);
  for (const [from, to] of [['POC 成功不等于生产可用','POC 成功就是生产可用'], ['生产可用不等于验收通过','生产可用就是验收通过'], ['验收通过不等于放量','验收通过就是放量'], ['放量不等于复制','放量就是复制'], ['AI 只负责检索、分类、生成候选或建议，不得最终授权不可逆动作','AI 最终授权不可逆动作'], ['程序负责权限校验、确定性规则、审计记录和回滚开关','程序把确定性规则交给概率模型'], ['人负责授权不可逆动作、决定放量与终止','AI 负责授权不可逆动作、决定放量与终止'], ['人工队列有上限、时限和能力约束','人工兜底无限且无时限'], ['客户业务负责人拥有明确停止权','停止权未指定'], ['NIST AI RMF 1.0 支持评估、监测与人工覆盖机制','NIST 说明市场规模为 100 亿元']]) { const mutation = mutate(source, from, to, from); assert.throws(() => assertEvidenceAndResponsibilities(mutation), assert.AssertionError); }
  const detachedHandler = mutate(source, "onKeyDown={handleHorizontalArrowKey}", 'onKeyDown={() => {}}', 'detached ArrowRight handler'); assert.throws(() => assertWrappersAndArrowBehavior(detachedHandler), assert.AssertionError);
  const {drawio, svg} = fixtureDiagram(); assertDiagram(drawio, svg); const laterMask = `${svg}<rect x="0" y="0" width="840" height="380" fill="#ffffff"/>`; assert.notEqual(laterMask, svg, 'later occluder mutation is non-no-op'); const diagramMutations = [['terminal port', mutate(drawio, 'exitX=1', 'exitX=0', 'terminal port'), svg], ['route identity', drawio, mutate(svg, 'data-edge-id="feedback-rollout-to-acceptance"', 'data-edge-id="feedback-copy"', 'route identity')], ['partial shared segment', drawio, mutate(svg, 'L 610 130 L 35 202.5', 'L 600 110 L 225 72.5', 'partial shared segment')], ['edge contrast', drawio, mutate(svg, '#1d4ed8', '#ffffff', 'edge contrast')], ['marker size', drawio, mutate(svg, 'markerWidth="18" markerHeight="18"', 'markerWidth="15" markerHeight="15"', 'marker size')], ['label collision and size', drawio, mutate(svg, 'x="600" y="92" font-size="16"', 'x="600" y="110" font-size="14"', 'label collision and size')], ['later opaque mask', drawio, laterMask]]; diagramMutations.forEach(([label, mutatedDrawio, mutatedSvg]) => assert.throws(() => assertDiagram(mutatedDrawio, mutatedSvg), assert.AssertionError, label));
});

test('MTH-07 locks the narrow method exception while every other method retains nine headings', () => { const source = requiredArticle().source; assertMetadataAndHeadings(source); for (const document of documents.filter(({file}) => file.startsWith('methods/') && file !== 'methods/index.mdx' && file !== 'methods/mth-07-fde-enterprise-ai-delivery.mdx')) { assert.equal(document.metadata.content_type, 'method', `${document.file} cannot escape through metadata`); assert.deepEqual(document.headings.filter(({level}) => level === 2).map(({text}) => `## ${text}`), knowledgeTypeContracts.method, document.file); } });
test('MTH-07 locks twelve auditable gate contracts', () => assertGateRows(requiredArticle().source));
test('MTH-07 locks citation-aware evidence and responsibility boundaries', () => assertEvidenceAndResponsibilities(requiredArticle().source));
test('MTH-07 locks governed source identities, exact relations, wrappers, density, and Stage A projection', () => {
  const source = requiredArticle().source; const record = ledger.documents[ARTICLE]; assert.deepEqual(record?.citations.map(({source_id}) => source_id), SOURCE_IDS); const sources = new Map(SOURCE_IDS.map((id) => [id, ledger.sources.find((item) => item.id === id)]));
  for (const [id, expected] of REMOTE_SOURCES) { const item = sources.get(id); assert.ok(item, id); for (const [field, value] of Object.entries(expected)) if (field !== 'allowed') assert.equal(item[field], value, `${id}.${field}`); assert.deepEqual(item.allowed_evidence_roles, expected.allowed ?? ['method'], `${id} schema-valid evidence roles`); assert.match(item.usage_boundary, /(?:摘要|summary|不.*(?:市场|薪资|政策)|not.*(?:market|salary|policy))/iu, `${id} citation boundary`); }
  assert.equal(new Set([...REMOTE_SOURCES.values()].map(({canonical_locator}) => new URL(canonical_locator).hostname)).size, 3, 'three independent remote domains'); const primary = record?.citations.filter(({manifest_primary}) => manifest_primary); assert.deepEqual(primary?.map(({source_id}) => source_id), ['src-wechat-fde-12-core-capabilities']); assert.deepEqual(primary?.[0]?.roles, ['historical-context'], 'WeChat primary is schema-valid practice context'); assert.equal(primary?.[0]?.usage_mode, 'facts-summary'); assert.match(primary?.[0]?.attribution_note ?? '', /实践框架|四阶段|十二/u); const illustration = sources.get('src-atlas-mth07-fde-delivery-gates'); assert.equal(illustration?.source_kind, 'original-illustration'); assert.equal(illustration?.license, 'LicenseRef-Atlas-Original'); assert.equal(illustration?.copyright_policy, 'original-atlas');
  assert.deepEqual(extractInternalLinks({body: article.body}), ['/cases/temporal-saga-durable-execution', '/methods', '/methods/mth-01', '/methods/mth-04', '/methods/mth-06']); const text = visible(source); assert.match(text, /Temporal.{0,60}(?:工程机制参照|不证明 FDE 组织模式)/u); assert.doesNotMatch(text, /QA-09/u); assert.deepEqual(extractExternalLinks({body: article.body}).sort(), [...REMOTE_SOURCES.values()].map(({canonical_locator}) => canonical_locator).sort()); assertWrappersAndArrowBehavior(source); assert.ok(analyzeCaseText(article.body).visualBalance.score > 90); assert.deepEqual({completed_topics: projectStatus.completed_topics, content_documents: projectStatus.content_documents, governed_sources: projectStatus.governed_sources}, {completed_topics: 59, content_documents: 102, governed_sources: 529}); const topic = manifest.topics.find(({id}) => id === TOPIC_ID); assert.equal(topic?.published, true); assert.equal(topic?.status?.value, 'pending');
});
test('MTH-07 diagram parses actual Draw.io terminals and rendered SVG geometry/style/painter parity', async () => { const [drawio, svg] = await Promise.all([readFile(new URL(`../${DRAWIO}`, import.meta.url), 'utf8'), readFile(new URL(`../${SVG}`, import.meta.url), 'utf8')]); assertDiagram(drawio, svg); });
