import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import test from 'node:test';

import {parseFrontMatter} from '../scripts/content-metadata.mjs';

const root = new URL('../', import.meta.url);
const requiredCaseSlugs = JSON.parse(
  await readFile(new URL('./fixtures/legacy-case-order.json', import.meta.url), 'utf8'),
).map(({slug}) => slug);

async function source(path) {
  return readFile(new URL(path, root), 'utf8');
}

test('uses one root autogenerated sidebar instead of duplicate manual categories', async () => {
  const sidebar = await source('sidebars.ts');

  assert.match(sidebar, /type:\s*'autogenerated'/);
  assert.match(sidebar, /dirName:\s*'\.'/);
  assert.doesNotMatch(sidebar, /label:\s*'案例库'/);
  assert.doesNotMatch(sidebar, /dirName:\s*'cases'/);
});

test('orders section index links with exact navigation copy', async () => {
  const expected = [
    ['content/intro.mdx', 1, '首页'],
    ['content/concepts/index.mdx', 2, '基础概念'],
    ['content/principles/index.mdx', 3, '架构原则'],
    ['content/quality-attributes/index.mdx', 4, '质量属性（Quality Attribute）'],
    ['content/methods/index.mdx', 5, '架构方法'],
    ['content/modeling/index.mdx', 6, '建模与图示'],
    ['content/styles/index.mdx', 7, '架构风格'],
    ['content/patterns/index.mdx', 8, '架构模式'],
    ['content/cases/index.mdx', 9, '案例库'],
    ['content/questions/index.mdx', 10, '设计题'],
    ['content/paths/index.mdx', 11, '学习路径'],
    ['content/references/index.mdx', 12, '资料库'],
    ['content/terminology.mdx', 13, '术语规范'],
  ];

  for (const [path, position, label] of expected) {
    const metadata = parseFrontMatter(await source(path));

    assert.equal(metadata.sidebar_position, position, path);
    assert.equal(metadata.sidebar_label ?? metadata.title, label, path);
  }
});

test('gives every canonical case a concise navigation-only label', async () => {
  for (const slug of requiredCaseSlugs) {
    const filename = slug.split('/').at(-1);
    const content = await source(`content/cases/${filename}.mdx`);
    const label = content.match(/^sidebar_label: (.+)$/m)?.[1];

    assert.ok(label, `Missing sidebar_label for ${slug}`);
    assert.ok(label.length <= 42, `Sidebar label is too long for ${slug}`);
    assert.doesNotMatch(label, /[：:]/, `Sidebar label contains a subtitle for ${slug}`);
  }

  assert.match(
    await source('content/cases/kong-ai-gateway-routing-resilience.mdx'),
    /^sidebar_label: 人工智能网关路由与恢复$/m,
  );
});

test('gives sidebar rows readable hierarchy and stable active feedback', async () => {
  const css = await source('src/css/custom.css');

  assert.match(css, /\.theme-doc-sidebar-menu\s*\{/);
  assert.match(
    css,
    /\.theme-doc-sidebar-menu \.menu__link\s*\{[^}]*min-height:\s*2\.5rem/s,
  );
  assert.match(
    css,
    /\.theme-doc-sidebar-menu \.menu__link--sublist\s*\{[^}]*font-weight:\s*650/s,
  );
  assert.match(
    css,
    /\.theme-doc-sidebar-menu \.menu__list \.menu__list\s*\{[^}]*padding-left:\s*0\.75rem/s,
  );
  assert.match(css, /text-overflow:\s*ellipsis/);
  assert.match(
    css,
    /\.theme-doc-sidebar-menu \.menu__link--active:not\(\.menu__link--sublist\)\s*\{[^}]*box-shadow:\s*inset 2px 0/s,
  );
  assert.doesNotMatch(
    css,
    /\.menu__link--active:not\(\.menu__link--sublist\)\s*\{[^}]*border-left:/s,
  );
});

test('keeps the mobile sidebar fixed to the viewport instead of the blurred navbar', async () => {
  const css = await source('src/css/custom.css');

  assert.match(
    css,
    /@media screen and \(max-width: 996px\)\s*\{[^}]*\.navbar\s*\{[^}]*backdrop-filter:\s*none/s,
  );
});
